src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/comments.php
tests/comments/jsfmt.spec.js

Added test case for comments and fixed printer to not add extra lines at beginning/end of docblocks

Removing extra line in docblocks

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
tests/functions/__snapshots__/jsfmt.spec.js.snap

I wanted to optimize the handling of long calls like this one:
```php
$this->something->method($argument, $this->more->stuff($this->even->more->things->complicatedMethod()));
```
which used to be turned into
```php
$this->something->method($argument, $this->more->stuff($this->even->more->
things->
complicatedMethod()));
```
and would now be turned into
```php
$this->something->method(
$argument,
$this->more->stuff($this->even->more->things->complicatedMethod())
);
```
This seems to be PSR-2 compliant as far as i can tell ([see here](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#46-method-and-function-calls)).
However, it's this would also change the way functions like `array_map` would be printed like:
```php
array_map(
function ($entry) { …
```

Optimize wrapping of long calls

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

Reusing solution from #14 for other functions that need to print multiple lines

Use multi-line print for all multi-line node types

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
tests/functions/__snapshots__/jsfmt.spec.js.snap
tests/functions/functions.php

Fixing pass by reference for functions and methods

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/comments.php

For multi-line comments (not docblocks) we weren't printing new lines

Fixing multi-line comments

---

src/printer.js
tests/formatting/__snapshots__/jsfmt.spec.js.snap
tests/include/__snapshots__/jsfmt.spec.js.snap
tests/include/include.php

Addressing #68 
[Namespace](https://github.com/glayzzle/php-parser/blob/master/docs/AST.md#namespace) is just an extension of a block node - we need to use `printLines` to actually print the `children` attribute

fix: use printLines for namespace nodes

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/constants/__snapshots__/jsfmt.spec.js.snap
tests/formatting/__snapshots__/jsfmt.spec.js.snap
tests/traits/__snapshots__/jsfmt.spec.js.snap

Information:
- Laravel - __No__ (https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Application.php)
- Symfony - __No__ (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpKernel.php)
- Yii2 - __No__ (https://github.com/yiisoft/yii2/blob/master/framework/BaseYii.php)

fix: remove extra line in top of body class

---

README.md
package.json
yarn.lock

Upgrades Prettier to https://github.com/prettier/prettier/commit/c1107a86dd088c5f12bf7cd2f23a4b7634708de3, which includes https://github.com/prettier/prettier/pull/4038, and fixes the issue reported in #55.

Upgrade Prettier to pre-1.11

---

src/clean.js
src/printer.js
tests/case/__snapshots__/jsfmt.spec.js.snap
tests/case/case.php
tests/case/jsfmt.spec.js

:star: 
Other improvement:
1. Support alternative syntax
2. NULL => `null`
3. magic constant to upper case `__line__` => `__LINE__`
Parser problem:
1. https://github.com/glayzzle/php-parser/issues/117

feat: lowercase all keywords

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/comments.php

fixes #30
Also i think we should don't touch content inside comments. Prettier don't do this and we should not do this.
If comment `//Foo` we should print `//Foo`, don't add example space. Let's do this in other PR

fix: multiline comments

---

src/printer.js
tests/foreach/__snapshots__/jsfmt.spec.js.snap
tests/foreach/foreach.php

@czosel @mgrip @vjeux @azz That do you think about this output? Should we print `as` always newline when group breaks?

tests: long `foreach`

---

tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

From PSR-12:
> The opening brace for the class MUST go on its own line; the closing brace for the class MUST go on the next line after the body.
> Opening braces MUST be on their own line and MUST NOT be preceded or followed by a blank line.
> Closing braces MUST be on their own line and MUST NOT be preceded by a blank line.

tests: empty lines between opening and closing braces

---

tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

From PSR-12:
> There MUST NOT be more than one property declared per statement.

tests: multiple properties and methods

---

tests/call/__snapshots__/jsfmt.spec.js.snap
tests/call/call.php

From PSR-12:
> When making a method or function call, there MUST NOT be a space between the method or function name and the opening parenthesis, there MUST NOT be a space after the opening parenthesis, and there MUST NOT be a space before the closing parenthesis. In the argument list, there MUST NOT be a space before each comma, and there MUST be one space after each comma.

tests: spaces in function and method declaration

---

src/printer.js
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php
tests/propertylookup/__snapshots__/jsfmt.spec.js.snap
tests/propertylookup/propertylookup.php

There are probably many cases where this still breaks, but it might be an improvement anyway :smile: 
#112

Fix dynamic propertylookup

---

src/printer.js
tests/propertylookup/__snapshots__/jsfmt.spec.js.snap
tests/propertylookup/propertylookup.php

This also adds a linebreak after an assignment operator if there is a literal on the right.
Fixes #150

Remove linebreak in propertylookup on left side of assignment

---

src/printer.js
tests/static/__snapshots__/jsfmt.spec.js.snap

As `global`, also as `var a,b,c,d;` in `prettier`

feat: improve `static` output

---

src/printer.js
src/util.js
tests/inline/__snapshots__/jsfmt.spec.js.snap
tests/inline/inline.php
tests/inline/mixed-1.php
tests/inline/mixed-2.php
tests/inline/mixed.php

It is not easy :+1:  Why remove `printLines`?
1. One place where we put `;` and `newlines`.
2. Easy reading.
3. For future: here we can add/remove unnecessary nodes(example - `parens` around arithmetic operation how it do `prettier` or better output `inline`).
After add `\n` in `php-parser` (already added, need just update) output will be more better :+1:

feat: improve `inline` output

---

src/printer.js
tests/eval/__snapshots__/jsfmt.spec.js.snap
tests/eval/eval.php

Rare use case, but we need good output :smile:

fix: better output `eval` node

---

src/index.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/array.php

Some comment will be printed better (as do prettier). We need implement `printComments` function as in prettier or move in shared utils. Let's merge this as is and in next PR fix comment places.

fix: print comments in array

---

src/printer.js
src/util.js
tests/echo/__snapshots__/jsfmt.spec.js.snap
tests/list/__snapshots__/jsfmt.spec.js.snap
tests/print/__snapshots__/jsfmt.spec.js.snap
tests/string/__snapshots__/jsfmt.spec.js.snap
tests/string/string.php

https://github.com/prettier/plugin-php/issues/29
Unfortunately I don't think we can fix https://github.com/prettier/plugin-php/issues/253 right now. Maybe we can utilize the `raw` attribute from the parser? But `node.value` is exactly the same whether its a literal line break or escaped

fix: add string escape for encapsed

---

CONTRIBUTING.md
LICENSE

I just noticed that the repo didn't include a license or contributing guidelines yet, so here's a first draft.
* MIT, just like prettier
* Mike holds the copyright, because he started with the plugin
* Contributing guidelines almost the same as for prettier, with some minor modifications.

Add license and contributing guide

---

src/index.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/dangling_for.php
tests/comments/do.php
tests/comments/for.php
tests/comments/foreach.php
tests/comments/if.php
tests/comments/switch.php
tests/comments/while.php

fixes #269
Also fix incorrect position comments for `foreach` and rename `dangling_for` to `for`

fix: don't print empty line in body of control structures for leading comments

---

src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/comments.php

fixes #303 fixes #268
Pretty much re-using the same logic from the js printer https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L5383

fix: only format printing of comments for docblocks

---

README.md
package.json

README update for alpha release

---

src/parser.js
tests/newline/CRLF.php
tests/newline/__snapshots__/jsfmt.spec.js.snap

just adding test for https://github.com/prettier/plugin-php/issues/262
Also stripping `\r\n` from the parser, according to https://github.com/glayzzle/php-parser/issues/155#issuecomment-384763532

tests: adding test for crlf docblocks

---

README.md

Global plugin discovery has landed in prettier core :tada: 
https://github.com/prettier/prettier/pull/4192
Shoutout to @kachkaev :100:

Global install is working!

---

README.md

`npm` requires `--` to append params to the script

Correct npm run instructions

---

README.md

I think we can recommend installing from npm now.

Readme: Install from npm

---

src/printer.js
tests/closure/__snapshots__/jsfmt.spec.js.snap
tests/closure/closure.php
tests/functions/__snapshots__/jsfmt.spec.js.snap
tests/functions/functions.php

Critical bug :smile: 
Also move all `closure` from `function` directory to `closure` directory

fix: print return type declaration for closure

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/blank_lines.php

fixes #368 
Need fix problem with inline (full refactor logic), before we can't solve problems with inline nodes we can't release stable version, I ask for help from everyone who is interested in stable release

fix: handle empty lines between comments in ast with children

---

src/printer.js
tests/declare/__snapshots__/jsfmt.spec.js.snap
tests/declare/declare.php

Rare use case, but found in our docs :smile:

fix: better print empty declare node

---

src/printer.js
tests/member_chain/__snapshots__/jsfmt.spec.js.snap
tests/propertylookup/__snapshots__/jsfmt.spec.js.snap
tests/variable/__snapshots__/jsfmt.spec.js.snap
tests/variable/variable.php

fixes #270 
Note: 
- Fix bug when we break `php5` code (http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect). All values should be printed as is, don't changed.
- Find bug in parser https://github.com/glayzzle/php-parser/issues/167
- Refactor `variable` inside `encapsed` (fast exit, increase perf)

fix: extra curly around variable

---

src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAbgQwE4AIC8uwAOlLrsSPAM4yb0ONPMutvseuVK4BmArlDAwAltFw0YACgCUJMuVzY4MftjKUAjJQDcpcgF9SBkABoQEAA6jo1ZKBzYIAdwAKOBHZSZ0EEQBMzEAAjbEwwAGsVAGVLcJEoAHNkGGx+OHME6jhsGFcwxIBbTGReTAAbbPMAK2oADwAhMMiYzEK4ABkEuFKKqpA47GzsZBDMYIBPcuggy2wEmAB1AJgAC2QADgAGczmIbMWwy1G5uGH0HvNlAEd+EWV8zCKSpDLKjJBswpEUtI-qBKJcpwACK-Ag8F673MdGCy38a2QABYYWEROVAQBhCCFYqjKDQS4gfjZAAq4y8b2yBgMQA
I started to integrate `prettier` for php in my projects, there is a lot of ugly code, but it is great we do not break it anywhere :star: 
In near future i will fix all ugly code and maybe we ready for a stable release

fix: better print `closure` in array

---

src/printer.js
tests/propertylookup/__snapshots__/jsfmt.spec.js.snap
tests/propertylookup/propertylookup.php

Running the tests with AST comparison brought this to my attention. Removing the curly braces in this context means `foo` is no longer being evaluated as a constant.

Be more specific about when to not wrap constref nodes in property lookups

---

src/printer.js

No changes, only move all nodes in on switch as prettier also do (https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L344).
Why?
1. Less call/switch (micro perf optimization).
2. Better add new nodes in future.
3. No need to think on type of node (`statement`, `literal`, `control structure` and etc)

refactor: printer

---

README.md

ALE is a popular vim linter that already supports Prettier plugins. I've been using it for a while and it's what I'd recommend to someone wanting to format PHP with Prettier.

Add great vim option

---

src/printer.js
tests/namespace/__snapshots__/jsfmt.spec.js.snap

fix: extra space in namespace without name

---

src/parser.js
src/printer.js
tests/markdown/__snapshots__/jsfmt.spec.js.snap
tests/markdown/markdown.md

Awesome :star: 
We support:
```php
$a=1;
```
```php
<?php
$a=1;
```
Some people use `<?php`, some not, let's support both

feat: markdown support

---

src/util.js
tests/inline/__snapshots__/jsfmt.spec.js.snap
tests/markdown/__snapshots__/jsfmt.spec.js.snap

this bug also exists in https://github.com/prettier/plugin-php/pull/550

fix: don't add extra newline in last inline node

---

src/printer.js
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/nowdoc.php

big bug, also better print their before `=`

fix: add newline after heredoc and nowdoc parameter

---

src/needs-parens.js
src/printer.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/yield.php
tests/yield/__snapshots__/jsfmt.spec.js.snap
tests/yield/yield.php

We always wrap yield in parens in many cases to avoid `Caution` from http://php.net/manual/en/language.generators.syntax.php and don't break code for `php5` and `php7`

feat: better print yield node

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/retif/__snapshots__/jsfmt.spec.js.snap

Let's output `parens` for all `nested` `retif`, ternary in `js` is difference than in `php` and it is really difficult to read their without `parens`.
But we can avoid parens for `test` and `trueExpr` properties, but i find this very ugly.
Without `trueExpr`:
```php
true ? 1 ? 2 : 3 : (4 ? 5 : 6); // Inconsistently and ugly
// vs
true ? (1 ? 2 : 3) : (4 ? 5 : 6);
```
Without `test`:
```php
1 ? 2 : 3 ? (1 ? 2 : 3) : (4 ? 5 : 6); // Looks ugly
vs
(1 ? 2 : 3) ? (1 ? 2 : 3) : (4 ? 5 : 6);
```

fix: broken `retif` without parens

---

src/index.js
src/util.js

Just remove unused `parenthesis` logic

refactor: remove unused stuff

---

src/parser.js
src/printer.js

reorder print logic for nodes with similar functionality, if somebody know how it can be better PR welcome. Also remove `extractTokens`, it should increase perf. Refactor `continue/break` nodes

refactor: stuff

---

src/printer.js

We can get `node` from `path`, no need pass this as argument

refactor: print declaration block

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap

We should separate functions for print `class`/class like nodes (`interface` and `trait`) and function/function like nodes (`closure` and `method`). Will be done in next PR. It is first part.

refactor: print `class`, `interface` and `trait` nodes

---

src/printer.js

Part 3. Why?
Main print function (`genericPrint(path, options, print)`) uses this arguments order, let's use this order everywhere.

refactor: standardize function arguments

---

src/printer.js
tests/identifier/__snapshots__/jsfmt.spec.js.snap
tests/identifier/identifier.php

fix: do not break code with `self`, `static` and `parent` identifier

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/retif.php

not same, but good for example https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAbgQwE4AIC8uGOuA-KUVnuZSTQOQDOM2AllAOb0DcAOlMTyEAFILIVBASnG1qFJi3Zc+AqgVzDRamlJm6GzNpx78xIzWJ1VpVnDfmGl9SSrMbLFLXQnX7uBUbKpmoiHhpecrJ+AU6SLsEkodqeYREyMcZxLiAANCAQAA4wrNCMyKA42BAA7gAKOAhlKJjoEKwAJrkgAEbYmGAA1nAwAMoF-UrILACucHnsjHDYMLV9HAC2mMgAZpgANot5AFaMAB4AQn2DwyOY63AAMuxwO-uHIOPYi9jIPZjdAE89tAugUjDAAOodGAAC2QAA4AAx5MEQRYQvoFX5guDfdAvPLYOAAR2mrCJq0wGy2SF2BzmIEW61YU2wszyjCUezgAEVphB4K96XkYP8oe1YcgAEwivqsPZKADCEHWm1+UGgBJA00WABV-k06YsAL7GoA

fix: avoid unnecessary parent around `retif` node without `trueExpr`

---

src/printer.js
tests/assign/__snapshots__/jsfmt.spec.js.snap
tests/assign/assign.php
tests/member_chain/__snapshots__/jsfmt.spec.js.snap

Why? Because `::` in js is not same in `php`

feat: consistently print assign node with lookup nodes

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/bin.php

fix: avoid unnecessary parens in `bin` with `and` or `or`

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/functions.php
tests/comments/method.php

Before we got Error about what we don't print comment

fix: trailing comment in `function` and `method` node

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/print.php

Looks we forget about this problem :smile:

fix: indent for `print` node with end of line comment

---

src/comments.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/return.php

fixes #764
Let's print `return` with comment(s) consistently, as we print other keywords with comment(s)

feat: print comment for `return` on same line

---

src/comments.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/if.php

Format comment as prettier for `if/else`, support comments between `if` and `elseif`, `elseif`  and `else`. Also i found this in `laravel` and `symfony`

feat: better print if comments

---

src/printer.js
tests/staticlookup/__snapshots__/jsfmt.spec.js.snap
tests/staticlookup/staticlookup.php

Add todo, when parser fix it we can remove this line

fix: consistent break assign for static lookup

---

src/index.js
src/printer.js
src/util.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/new.php
tests/declare/__snapshots__/jsfmt.spec.js.snap
tests/declare/declare-invalid.php
tests/declare/declare-multiple-statements-2.php
tests/declare/declare-multiple-statements.php
tests/new/__snapshots__/jsfmt.spec.js.snap
tests/new/new.php

Also add more tests. 
Why i change output for anonymous class? Because it is looks really ugly in real use case.
Example.
Now:
```php
public static function createLogger($arg) {
$logger = new class(
$arg['type'],
$arg['severity'],
$arg['filter'], 
$arg['bail'] 
) extends BaseLogger {};
$logger->init();
return $logger;
}
```
Before:
```php
public static function createLogger($arg) {
$logger = new class(
$arg['type'],
$arg['severity'],
$arg['filter'], 
$arg['bail'] 
) extends BaseLogger {
};
$logger->init();
return $logger;
}
```
Before example have ugly `{` and `}`, there is no reason to add newline after `{`.

refactor: anonymous class

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/control-structures.php

fixes #731 
Prettier to `js` add parens for assign in control structure, but i think it is good for js, but not for php. Why?
- Popular PHP packages avoid parens (`laravel`, `symfony`, `WordPress` and etc)
- Many built-in `PHP` function return `false`/`null` and many developers using (to avoid extra code):
```php
$file = null;
if ($file = file_get_contents($var)) {
}
```
With parens it is look very ugly

fix: avoid parens for `assign` in control structure

---

src/printer.js
tests/namespace/__snapshots__/jsfmt.spec.js.snap
tests/namespace/namespace-resolution.php

We can break code in some places without this, so it is bug fix

fix: namespace rn resolution

---

src/printer.js
src/util.js
tests/inline/__snapshots__/jsfmt.spec.js.snap
tests/inline/declare-1.php

From https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md
Example:
```php
<?php declare(strict_types=1) ?>
<html>
<body>
<?php
// ... additional PHP code ...
?>
</body>
</html>
```

fix: avoid semicolon for declare and inline

---

src/printer.js
tests/magic/__snapshots__/jsfmt.spec.js.snap
tests/magic/magic.php

fix: add curly when offset is magic node in staticlookup

---

package.json
src/comments.js

Some bugs still exists in parser around `cast` and `silent` node

refactor: remove outdated todo from tests

---

tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/chains.php

Some comment for `offsetlookup` and `staticlookup` have invalid position, but it is already have the PR https://github.com/glayzzle/php-parser/pull/249, but they related to other issues  https://github.com/prettier/plugin-php/issues/890 and https://github.com/prettier/plugin-php/issues/891, so we update snapshot after update parser again
fixes #870

test: comment in lookup

---

src/needs-parens.js
tests/call/__snapshots__/jsfmt.spec.js.snap
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/call.php
tests/parens/control-structures.php

fixes #857
It is really popular practice in many code bases like `laravel`, `symfony`, `wordpress` and etc.

fix: avoid extra parens around call argument

---

src/printer.js
src/util.js

prepare for #829, also refactor, now we use `printBodyControlStructure` for all `control` structures, it is allow improve `inline` node printing for some cases

refactor: try/catch/finally

---

.appveyor.yml
.travis.yml
package.json
src/printer.js
src/util.js
tests/classconstant/__snapshots__/jsfmt.spec.js.snap
tests/classconstant/classconstant.php
tests/constant/__snapshots__/jsfmt.spec.js.snap
tests/constant/constants.php
yarn.lock

Includes:
- Change `static` ast printing
- Fixed `constantstatement` and `classconstant` printing with `value` as prettier format `const`/`let`/`var`
- Tests
Before we use same algorithm for `*constant` and `static` nodes. Now they are same in some places, but it is really difference ast, also `*constant` nodes ast will be changed in near future

chore: deps update parser

---

src/printer.js
tests/preserve_line/__snapshots__/jsfmt.spec.js.snap
tests/preserve_line/traituse.php

Just refactor + tests, increase print speed, `traituse` can't contain inline nodes

refactor: simplify code for `traituse` node

---

src/printer.js
tests/preserve_line/__snapshots__/jsfmt.spec.js.snap
tests/preserve_line/class.php

Refactor + tests, `class`/`trait`/`interface` can't contain `inline`

refactor: simplify class body printing

---

src/clean.js
src/printer.js
src/util.js
tests/case/__snapshots__/jsfmt.spec.js.snap
tests/case/magic-methods.php

Normalize case of magic methods, PHP allow use any case for this (like `__CONSTRUCT`, `__CoNsTrUcT`, '`__construct`) and all cases are valid and works, so let's normalize case of them to lower

feat: normalize case of magic methods

---

src/printer.js
tests/brace-style/__snapshots__/jsfmt.spec.js.snap
tests/brace-style/methods.php
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/parameter/__snapshots__/jsfmt.spec.js.snap

fixes #929
Looks we already have invalid printing in our code. Also we need implement `printFunctionParams` for function and method, now we use `printArgumentsList` and it is may output ugly paramaters in some very rare cases, also it is increase printing time. Let's do it in other PR

fix: better print multiline function and method declaration

---

package.json
src/parser.js
tests/syntax-error/__snapshots__/jsfmt.spec.js.snap
tests/syntax-error/jsfmt.spec.js
tests_config/get_engine.js
tests_config/run_spec.js

This PR changes the structure of `SyntaxError`s thrown from the PHP plugin towards Prettier in such a way that Prettier knows how to handle them, as explained in #956.
The small refactoring in the `tests_config` folder is a necessity for the added test that covers the new behavior, as this test is not matching the structure of the other `run_spec()` tests.

Implement Syntax Errors Matching Prettier Conventions, fixes #956

---

README.md

I found this workaround in
https://github.com/prettier/plugin-ruby/issues/113 and confirmed that it
works. "Run on save" stopped working for me a while ago, so I'd
recommend using prettier-vscode with the workaround instead.

Docs: Describe workaround for prettier-vscode

---

src/comments.js

Backport: https://github.com/prettier/prettier/pull/5930#issuecomment-469053975

fix: trailing comment output when the printer returns a doc instead of a string

---

src/util.js
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/nowdoc.php

I found a formatting bug where heredoc inside of a function call inside of a second function call would format to a syntax error due to a comma being added after the heredoc delimiter.
Input:
```
$str = sprintf(sprintf(<<<EOD
foo
EOD
, true));
```
prettier output:
```
$str = sprintf(
sprintf(
<<<EOD
foo
EOD, 
true
)
);
```
correct output:
```
$str = sprintf(
sprintf(
<<<EOD
foo
EOD
, 
true
)
);
```

Fixed heredoc inside function calls inside other function calls

---

src/util.js
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/nowdoc.php

There is a bug with heredoc inside of an array inside of a function call formatting to a syntax error.
Input:
```
$str = call(array(<<<END
foo
END
, true));
```
prettier php output with syntax error:
```
$str = call(array(
<<<END
foo
END, 
true
));
```
this pr output:
```
$str = call(array(
<<<END
foo
END
, 
true
));
```

 Fixed a bug with heredoc inside of an array inside of a function call

---

tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/chains.php

maybe we just copy tests from js, because `.` in JS is not same in PHP :smile:

test: fix invalid test

---

package.json
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/nowdoc.php
yarn.lock

This is just updating the parser - how we want to support the flexible heredoc/nowdoc feature introduced in PHP 7.3 still needs to be discussed.

fix: flexible heredoc/nowdoc syntax

---

package.json
src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/bin.php
yarn.lock

This adds support for the spread operator for arrays (PHP 7.4) and fixes
an issue with silent / retif precedence.
Fixes #1009

feat: update parser

---

jest.config.js
package.json
yarn.lock

This PR removes the build process and Jest run for [standalone tests](README.md#in-the-browser) from the regular `test` script.
The build step can still be invoked via `yarn build-standalone`. The `test` script can be run including standalone tests when providing a `RUN_STANDALONE_TESTS` environment variable set to `true`.
Previously, only the build step was part of the `prepublishOnly` script. This PR complements that with a full test run to ensure standlone tests are still used before releasing a new version.
This PR also adds two new dev dependencies:
- [`cross-env`](https://www.npmjs.com/package/cross-env) for setting the `RUN_STANDALONE_TESTS` environment variable in a CMD-compatible way (yay for Windows users).
- [`yarpm`](https://www.npmjs.com/package/yarpm): Previously, the …

Skip standalone build & test in development

---

package.json
tests/number/__snapshots__/jsfmt.spec.js.snap
tests/number/number.php
yarn.lock

Related to https://github.com/prettier/plugin-php/issues/854

chore: update parser to add numeric literal separator support

---

README.md
src/index.js
tests/ignore/__snapshots__/jsfmt.spec.js.snap
tests/ignore/ignore.php

Without this, `prettier-ignore-start`  is interpreted just like `prettier-ignore`:
In:
```php
// prettier-ignore-start
$foo     = "bar";
$foo     = "bar";
$foo     = "bar";
// prettier-ignore-end
```
Out:
```php
// prettier-ignore-start
$foo     = "bar";
$foo = "bar";
$foo = "bar";
// prettier-ignore-end
```

fix: remove broken handling of prettier-ignore-start and -end, docs

---

build/rollup.config.js
build/shims/assert.js
build/shims/buffer.js
jest.config.js
package.json
src/clean.js
src/comments.js
src/index.js
src/needs-parens.js
src/options.js
src/parser.js
src/pragma.js
src/printer.js
src/util.js
tests/markdown/jsfmt.spec.js
tests/syntax-error/jsfmt.spec.js
tests/trailing_commas/jsfmt.spec.js
tests_config/run_spec.js
yarn.lock

Prettier 2.0 brought some breaking changes with it ([see here](https://prettier.io/blog/2020/03/21/2.0.0.html#plugin-api-changes-in-prettierutil-6993httpsgithubcomprettierprettierpull6993-by-fiskerhttpsgithubcomfisker)). This implements the new API in a backwards-compatible way. CI currently doesn't proof the fact that it still works with 1.x, and since the breaking changes are few and nicely encapsulated, I'd keep CI as is.
Fixes #1352

fix: compatibility with prettier 2.0

---

src/printer.js
tests/arrowfunc/__snapshots__/jsfmt.spec.js.snap
tests/arrowfunc/arrowfunc.php

Not that commonly used but [static arrow functions are supported](https://wiki.php.net/rfc/arrow_functions_v2#this_binding_and_static_arrow_functions). Prettier was stripping the static declaration, so this PR preserves it if set. It also adds support for declared return types.

Support static & return-typed arrow functions

---

CONTRIBUTING.md
package.json
src/printer.js
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/jsfmt.spec.js
tests/trailing_commas/__snapshots__/jsfmt.spec.js.snap
yarn.lock

Fixes #1292
Fixed #854 
Turns out to be quite tricky to implement the rule suggested in https://github.com/prettier/plugin-php/issues/1274#issuecomment-570709723 - this is a simpler version.

feat: print flexible nowdoc

---

README.md

We're using the plugin successfully in production since more than one year - I think it's safe to remove the "alpha" label and instead be more specific about what still doesn't work well (inline support).

fix(docs): remove "not ready for production" label

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/assign.php
tests/comments/closure.php
tests/comments/variable.php

This removes the special handling we had for "array", "string" and
"encapsed" in favor of a more generic way to handle comments inside
assignments. With this approach, comments between the assignment
operator (equal sign) and the value are preserved as leading comments.
Fixes #1425

feat(comments): optimize printing of comments in assignments

---

package.json
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/bin.php
yarn.lock

Upstream PR: https://github.com/glayzzle/php-parser/pull/549
Fixes #1421

fix: update parser to fix precedence of ** and ??

---

docs/recipes/php-cs-fixer/PrettierPHPFixer.php
docs/recipes/php-cs-fixer/README.md

Hey,
Instead of writing a temporary file, Prettier's output can be processed directly if the second parameter of `exec` is set. This simplifies the fixer and should make it a bit more efficient.
I've tested this with a Symfony codebase with around 950 files and everything seemed fine. On my machine with a SSD the change had little impact on performance, but if an HDD is used, it might.
What do you think?

PrettierPHPFixer - Use output of exec directly instead of writing temporary file

---

src/printer.js
tests/call/__snapshots__/jsfmt.spec.js.snap
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/member_chain/__snapshots__/jsfmt.spec.js.snap
tests/member_chain/member_chain.php

As suggested here https://github.com/prettier/plugin-php/issues/1386#issuecomment-627439042, I've committed as a pull request my starting point to implement the same heuristic as Prettier js for chain breaking. In particular, prettier PHP formats as follows:
```php
$db
->setQuery()
->setValue()
->execute();
```
Whereas prettier js has adopted a style of keeping the first call on the same line as the parent when the parent is shorter than the indent size, as follows:
```php
$db->setQuery()
->setValue()
->execute();
```
I briefly started trying to implement this, and got as far as putting some test data in (probably the most valuable part of this PR), but I don't know enough about prettier to figure out whether the parent is at the beginning of a line. Without that, the change would cause a …

feat: update chain breaking heuristic

---

src/printer.js
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php

This fixes #1593
Seems like the support of flexible HereDoc accidentally broke multiline string with encapsed variable.

Fix indent on multiline string on version >= 7.3

---

package.json
yarn.lock

Needed for yarn2 compatibility.
Fixes #1754

fix(deps): use full commit hash for parser dependency

---

package.json
src/printer.js
tests/trailing_comma_func/__snapshots__/jsfmt.spec.js.snap
tests/trailing_comma_func/function.php
tests/trailing_comma_func/jsfmt.spec.js
yarn.lock

This patch requires the PHP parser support for hanging commas https://github.com/glayzzle/php-parser/pull/756
closes #1759

feat(php8 hanging comma) Add support for haning comma for functions, closures, arrow functions and methods

---

.github/workflows/nodejs.yml

Node 13 is no longer supported by the NodeJS Foundation, we should focus on currently supported versions.

feat(CI) Update NodeJS versions to current stable releases

---

package.json

Jest was warning about the config in package.json:
```
Multiple configurations found:
* /home/christian/dev/plugin-php/jest.config.js
* `jest` key in /home/christian/dev/plugin-php/package.json
Implicit config resolution does not allow multiple configuration files.
Either remove unused config files or select one explicitly with `--config`.
```

fix: remove jest config from package.json

---

src/needs-parens.js
src/printer.js
src/util.js
tests/nullsafepropertylookup/__snapshots__/jsfmt.spec.js.snap
tests/nullsafepropertylookup/offsets.php

Fixes #1900 
This makes multiline method chaining like:
```php
$a
->bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb()
?->ccccccccccccccccccccccccccccccc()
->dddddddddddddddddddddddddddddddd();
```
Work correctly when the nullsafe operator `?->` is used somewhere
in the chain.
Output before this PR:
```php
$a->bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb()
?->ccccccccccccccccccccccccccccccc()->dddddddddddddddddddddddddddddddd();
```
Ouput after this PR:
```php
$a
->bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb()
?->ccccccccccccccccccccccccccccccc()
->dddddddddddddddddddddddddddddddd();
```

Fix member chain when nullsafe operator is used

---

tests/functions/__snapshots__/jsfmt.spec.js.snap
tests/functions/functions.php

Part of https://github.com/prettier/plugin-php/issues/1691 
PHP 8.1 added the `never` return type. This PR add a unit test to make sure it is supported.
https://php.watch/versions/8.1/never-return-type

[8.1] Add test for covering 'never' return type

---

src/printer.js
tests/attributes/__snapshots__/jsfmt.spec.js.snap
tests/attributes/attributes.php

This fix excludes the function block attributes from the function definition, when chcking the line length.
closes #1870

Fix for function curly brace with attrs

---

src/clean.js
src/index.js
src/parser.js
src/pragma.js
src/printer.js

Prettier core normalize line breaks to `\n` before sending to plugin.

Remove handling `\r`

---

README.md

As per the conversation on the following issue, this issues seeks to include some additional details regarding caveats with VS Code.
https://github.com/prettier/plugin-php/issues/1730#issuecomment-1589426226
I am open to any and all improvements here and would welcome some additional testing, I have prepared a codespace repository to make this easier should anyone wish to take a look (just click the following link and press `.` on your keyboard).
https://github.com/WazzaJB/prettier-php-sample
I have used PNPM in the repository, but also trialed this there with npm and yarn (in case module resolution worked differently at all).

VS Code Documentation Update

---

src/printer.js
src/util.js
tests/case/__snapshots__/jsfmt.spec.js.snap
tests/case/magic-methods.php

Input:
```php
<?php
class Foo
{
public function __pRoTo__() {}
public function cOnStRuCtOr() {}
}
```
Output:
```php
<?php
class Foo
{
public function Have not implemented kind undefined yet.()
{
}
public function Have not implemented kind undefined yet.()
{
}
}
```

Fix magic methods detection

---

src/printer.js
tests/match/__snapshots__/jsfmt.spec.js.snap
tests/match/match.php

This updates `match($cond)` printing to ... er ... match `if ($cond)` (etc) when the condition can't fit onto a single line.
```php
match($really_really_really_really_really_really_really_really_long_variable_name) {
default => null
};
```
```php
match(
$really_really_really_really_really_really_really_really_long_variable_name
) {
default => null
};
```
```php
match(
$really_really_really_really_really_really_really_really_long_variable_name
) {
default => null
};
```
I added a test to the snapsnots, and this change also corrects/changes one of the other `match` snapshots.

fix(match): Indent match conditions

---

src/printer.mjs
tests/class/__snapshots__/jsfmt.spec.mjs.snap
tests/class/class.php

This change allows to use this plugin along with "PER Coding Style 2.0"
formating :
`readonly final class ClassName {}`
to
`final readonly class ClassName {}`
doc:
https://www.php-fig.org/per/coding-style/#46-modifier-keywords

feat: make format compatible with "PER Coding Style 2.0"

---

src/options.mjs
tests/single-quote-api/jsfmt.spec.mjs

This PR fixes #2302. `singleQuote` option regression on format API.
- Fixes: #2302
Added test for format api call. Please point out if this test method is not allowed in this project.

fix: 🐛 singleQuote option does not work on format API

---

src/printer.mjs
src/util.mjs
tests/member_chain/__snapshots__/jsfmt.spec.mjs.snap
tests/member_chain/offsetlookup.php

I have adjusted chain breaks for nested lookups which were overlooked in previous pull request. Also the break should now be consistent between `Test::foo()->`, `(new Test())->`, `$test['foo']` etc.

Adjustment for overlooked nested lookups in chain breaks

---

README.md

docs: add a clear note that we do not strictly follow PSR/PER

---

README.md

Currently, global install doesn’t work out of box: https://github.com/prettier/prettier/issues/15141#issuecomment-1902669174.
The section on vim points to an issue (fixed since 2018), giving the impression that it requires extra configuration. (For instance, the author of https://peterbabic.dev/blog/prettier-php-plugin-in-vim/ got confused by this wording.)
This PR updates both sections to provide up-to-date information.

Flag global install issue and update vim-prettier support info

---

tests/nullsafepropertylookup/__snapshots__/jsfmt.spec.mjs.snap
tests/nullsafepropertylookup/reserved-keyword.php
yarn.lock

This PR bumps php-parser dependency from 3.1.5 to 3.2.1
- added test for php keyword after null safe lookup fixed at https://github.com/glayzzle/php-parser/releases/tag/3.2.0

chore(deps): 🤖 bump php-parser from 3.1.5 to 3.2.1

---

README.md

Atom is archived project since December 2022 
https://github.blog/news-insights/product-news/sunsetting-atom/

docs: delete Atom code editor from the README.md

---

package.json
src/options.mjs
src/printer.mjs
tests/class/__snapshots__/jsfmt.spec.mjs.snap
tests/class/class.php
yarn.lock

Updated version of #2396
cc @mreiden

feat: add support for PHP 8.3 typed class constants

---

package.json
src/needs-parens.mjs
src/options.mjs
src/parser.mjs
src/printer.mjs
src/util.mjs
tests/new/__snapshots__/jsfmt.spec.mjs.snap
tests/new/jsfmt.spec.mjs
tests/parens/__snapshots__/jsfmt.spec.mjs.snap
tests/parens/jsfmt.spec.mjs
tests/parens/new.php
yarn.lock

This adds support for formatting things like `(new Foo())->bar` as `new Foo()->bar`. Support for this syntax was [added in PHP 8.4](https://www.php.net/releases/8.4/en.php#new_without_parentheses) and [very recently merged and released](https://github.com/glayzzle/php-parser/pull/1146) in php-parser. 
~~**Note** that php-parser 3.2.2 introduced a parser bug that affects how we format specifically placed comments in class constant assignments. My opinion is that this is an extreme edge case issue and it's worth the temporary regression in order to gain support for one of the highlighted features of php 8.4. (There is already a [pending PR](https://github.com/glayzzle/php-parser/pull/1152) to fix this in php-parser, and we can rollout an update to fix it here when that lands.~~ edit: this …

feat: format new without parenthesis in PHP 8.4

---

README.md

As added in https://github.com/prettier/plugin-php/pull/2422

update README: note php 8.4 compatibility
