prettier/plugin-php

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
tests/errors/__snapshots__/jsfmt.spec.js.snap
tests/errors/errors.php
tests/errors/jsfmt.spec.js

Trying to figure out why it didn't pass CI in #1

Adding errors

---

README.md
package.json

Just published current code as `0.0.0-development` - https://www.npmjs.com/package/@prettier/php

Switch to scoped @prettier package

---

src/printer.js

Refactor printNode to print

---

README.md
package.json

Looking to make the plugins more friendly to contributors, and better recognise the core contributors.

Add maintainers to README

---

.travis.yml
package.json
src/index.js
src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/constants/__snapshots__/jsfmt.spec.js.snap
tests/do/__snapshots__/jsfmt.spec.js.snap
tests/for/__snapshots__/jsfmt.spec.js.snap
tests/foreach/__snapshots__/jsfmt.spec.js.snap
tests/functions/__snapshots__/jsfmt.spec.js.snap
tests/goto/__snapshots__/jsfmt.spec.js.snap
tests/if/__snapshots__/jsfmt.spec.js.snap
tests/interface/__snapshots__/jsfmt.spec.js.snap
tests/kitchen_sink/__snapshots__/jsfmt.spec.js.snap
tests/kitchen_sink/kitchen_sink.php
tests/operations/__snapshots__/jsfmt.spec.js.snap
tests/sys/__snapshots__/jsfmt.spec.js.snap
tests/traits/__snapshots__/jsfmt.spec.js.snap
tests_config/run_spec.js
yarn.lock

Even though this is still work in progress, I thought I'd share this already because the way locations are specified by the PHP parser seems to require patching prettier core -
see https://github.com/czosel/prettier/commit/0d8251b99969f5e8f1e7207213379dc23254d8ca
It's a small change and seems reasonable to me, but maybe someone knows a better way to do this?

Fix line spacing - refs #7

---

src/printer.js
tests/for/__snapshots__/jsfmt.spec.js.snap
tests/kitchen_sink/__snapshots__/jsfmt.spec.js.snap

Add spaces after semicolons in for loops

---

src/printer.js
tests/functions/__snapshots__/jsfmt.spec.js.snap
tests/functions/functions.php

Until the parser issue is fixed, want to get this working to move forward with large-scale testing. Lets make sure to keep #36 open though

Hacky fix for array and callable types

---

src/printer.js
tests/for/__snapshots__/jsfmt.spec.js.snap
tests/for/for.php

Handle multiple expressions in for loops

---

src/printer.js
tests/use/__snapshots__/jsfmt.spec.js.snap
tests/use/jsfmt.spec.js
tests/use/use.php

fix: `use` keyword

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
tests/functions/__snapshots__/jsfmt.spec.js.snap
tests/functions/functions.php

Add return type support for functions and methods

---

tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php

tests: a lot of arrays test

---

src/printer.js
tests/formatting/__snapshots__/jsfmt.spec.js.snap
tests/use/__snapshots__/jsfmt.spec.js.snap
tests/use/without-namespace.php

fix: don't output extra semicolon

---

src/printer.js
tests/if/__snapshots__/jsfmt.spec.js.snap
tests/if/if.php

Adding semicolon for retif on own line

---

README.md

Add @evilebottnawi to list of maintainers

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
tests/functions/__snapshots__/jsfmt.spec.js.snap
tests/functions/functions.php

fix: functions and methods returning values by reference

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

fix: `abstract` method

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/comments.php

fix: comments with incorrect spacing

---

tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php

tests: arrays

---

tests/functions/__snapshots__/jsfmt.spec.js.snap
tests/functions/functions.php

tests: functions

---

tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
tests/interface/__snapshots__/jsfmt.spec.js.snap
tests/interface/interface.php

tests: iterables

---

tests/include/__snapshots__/jsfmt.spec.js.snap
tests/include/include.php

tests: include

---

tests/cast/__snapshots__/jsfmt.spec.js.snap
tests/cast/cast.php
tests/cast/jsfmt.spec.js

Parser problem:
https://github.com/glayzzle/php-parser/issues/119
In future we can discussion about `int` vs `integer` and etc.

tests: cast

---

src/printer.js
tests/eval/__snapshots__/jsfmt.spec.js.snap
tests/eval/eval.php
tests/eval/jsfmt.spec.js

Separate https://github.com/prettier/plugin-php/pull/73/files

feat: implement eval

---

src/printer.js
tests/switch/__snapshots__/jsfmt.spec.js.snap
tests/switch/switch.php

fix: unnecessary newline between case

---

src/printer.js
tests/exit/__snapshots__/jsfmt.spec.js.snap
tests/exit/exit.php

tests: exit

---

tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

> Opening braces for methods MUST go on the next line, and closing braces MUST go on the next line after the body.
Ref: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md

tests: method newline

---

tests/switch/__snapshots__/jsfmt.spec.js.snap

fix: get tests passing

---

tests/if/__snapshots__/jsfmt.spec.js.snap
tests/if/if.php

tests: `else if` control structure

---

src/printer.js
tests/exit/__snapshots__/jsfmt.spec.js.snap
tests/exit/exit.php
tests/halt/__snapshots__/jsfmt.spec.js.snap
tests/halt/halt.php
tests/halt/jsfmt.spec.js

fix: remove extra newline after halt

---

src/index.js
src/options.js
src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/jsfmt.spec.js
tests/functions/__snapshots__/jsfmt.spec.js.snap
tests/functions/jsfmt.spec.js
tests/interface/__snapshots__/jsfmt.spec.js.snap
tests/interface/jsfmt.spec.js
tests/kitchen_sink/__snapshots__/jsfmt.spec.js.snap
tests/kitchen_sink/jsfmt.spec.js
tests/namespace/__snapshots__/jsfmt.spec.js.snap
tests/return/__snapshots__/jsfmt.spec.js.snap
tests/traits/__snapshots__/jsfmt.spec.js.snap
tests/traits/jsfmt.spec.js
tests/yield/__snapshots__/jsfmt.spec.js.snap

Creating option for moving opening declaration brace to new line

---

src/printer.js
tests/constants/__snapshots__/jsfmt.spec.js.snap
tests/constants/constants.php

fixes #111 
Related: https://github.com/glayzzle/php-parser/issues/118 we need path release php-parser and update tests

fix: don't remove const scope

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

Remove line break for class properties

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
tests/functions/__snapshots__/jsfmt.spec.js.snap
tests/functions/functions.php

fixes https://github.com/prettier/plugin-php/issues/36#issuecomment-367980171

fix: nullable types

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/anonymous.php

:star: 
I think about pretty output we can have discussion in future, right now don't break code.

fix: anonymous classes

---

tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
tests/functions/__snapshots__/jsfmt.spec.js.snap
tests/functions/functions.php

tests: void functions

---

tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
tests/functions/__snapshots__/jsfmt.spec.js.snap
tests/functions/functions.php

tests: object type

---

tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php

tests: array `offsetlookup` using `identifier`

---

src/printer.js
tests/call/__snapshots__/jsfmt.spec.js.snap
tests/call/call.php
tests/call/jsfmt.spec.js

feat: `variadic` node

---

src/printer.js
src/util.js
tests/do/__snapshots__/jsfmt.spec.js.snap
tests/if/__snapshots__/jsfmt.spec.js.snap
tests/if/if.php

https://github.com/prettier/plugin-php/issues/139

fix: multi-line conditions

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

Remove linebreak in no-argument constructors

---

src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php

Fix indentation in offsetlookup

---

src/printer.js
tests/case/__snapshots__/jsfmt.spec.js.snap
tests/for/__snapshots__/jsfmt.spec.js.snap
tests/for/for.php

Based on `prettier` https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L1481

fix: empty `for`

---

src/printer.js
tests/while/__snapshots__/jsfmt.spec.js.snap
tests/while/while.php

PSR-12: https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#53-while-do-while

fix: indent in long `while` test

---

tests/do/__snapshots__/jsfmt.spec.js.snap
tests/do/do.php

Just tests.
PSR-12: https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#53-while-do-while

tests: long test in `do`

---

tests/closure/__snapshots__/jsfmt.spec.js.snap
tests/closure/closure.php
tests/closure/jsfmt.spec.js

PSR-12: https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#7-closures

tests: closures

---

tests/statement/__snapshots__/jsfmt.spec.js.snap
tests/statement/jsfmt.spec.js
tests/statement/statement.php

Just tests. From PSR:
> There MUST NOT be more than one statement per line.

tests: multiple statements per line

---

tests/switch/__snapshots__/jsfmt.spec.js.snap
tests/switch/switch.php

tests: statement between case without break

---

src/printer.js
tests/switch/__snapshots__/jsfmt.spec.js.snap
tests/switch/switch.php

PSR-12: https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#52-switch-case

fix: indent in long `switch` test

---

tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

From PSR-12: https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#45-method-and-function-arguments

tests: long function with type declaration

---

src/printer.js
tests/if/__snapshots__/jsfmt.spec.js.snap
tests/if/if.php

fix: short form only if

---

src/printer.js
tests/inline/__snapshots__/jsfmt.spec.js.snap
tests/inline/inline.php
tests/inline/jsfmt.spec.js
tests/inline/mixed.php
tests/inline/only-html.php

Feedback welcome :+1: 
Bug: https://github.com/glayzzle/php-parser/issues/120

feat: inline

---

src/printer.js
tests/operations/__snapshots__/jsfmt.spec.js.snap
tests/operations/operations.php

fix: breaking assignments for binary expressions onto newline

---

src/printer.js
tests/if/__snapshots__/jsfmt.spec.js.snap
tests/if/if.php

fix: adding indentation when parens break

---

src/printer.js
tests/closure/__snapshots__/jsfmt.spec.js.snap
tests/kitchen_sink/__snapshots__/jsfmt.spec.js.snap
tests/kitchen_sink/kitchen_sink.php

fix: nested if formatting in function parameter

---

src/printer.js
tests/global/__snapshots__/jsfmt.spec.js.snap

Based on https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAToDTYBGBYpZ5FlV1NtdVA3CHiBAA4wCW0AzsqFkwQA7gAUsCPinSoInACbMQ6HjGQAzdABsecFoUzowAazgwAymyOcoAc2QxMAVz0h5EMBu26WN3ZhhRQ1sAW3QvHVcAKx4ADwAhQxMzc3QQuAAZGzgIn1YnGDYCgCZc1ytMf2QQQnRCAE8taCU2TBsYAHUFGAALZAAOAAYWVohdDsM2ata4f1Qclkw4AEcnTiWg9FDwpE1Ill0QzgdnVx4bWy04AEUnCHgylhg6rvle5GKnw04tC4BhCAhMLVKDQBYgJy6AAqdSke10AF8EUA

fix: better output multiple items in global

---

tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php

tests: empty offset

---

src/printer.js
tests/offsetlookup/__snapshots__/jsfmt.spec.js.snap
tests/offsetlookup/jsfmt.spec.js
tests/offsetlookup/offsetlookup.php

:star: 
Based on prettier output

feat: improve long offset lookup output

---

src/printer.js
tests/call/__snapshots__/jsfmt.spec.js.snap
tests/call/call.php
tests/closure/__snapshots__/jsfmt.spec.js.snap

Function call wrapping, part 2

---

tests/trailing_whitespace/__snapshots__/jsfmt.spec.js.snap
tests/trailing_whitespace/jsfmt.spec.js
tests/trailing_whitespace/trailing_whitespace.php

PSR-12: 
> There MUST NOT be trailing whitespace at the end of lines.
Just tests

tests: trailing whitespace

---

tests/new/__snapshots__/jsfmt.spec.js.snap
tests/new/new.php

Just tests. Also change order in tests for better reading.

tests: `new` with variable

---

src/printer.js
tests/use/__snapshots__/jsfmt.spec.js.snap
tests/use/use.php

From PSR-12:
```php
use Vendor\Package\SomeNamespace\{
SubnamespaceOne\ClassA,
SubnamespaceOne\ClassB,
SubnamespaceTwo\ClassY,
ClassZ
};
```

feat: better output group use

---

src/clean.js
src/printer.js
tests/return/__snapshots__/jsfmt.spec.js.snap
tests/return/return.php

fixes #187
Based: https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L902

fix: `return` indent

---

src/printer.js
tests/use/__snapshots__/jsfmt.spec.js.snap
tests/use/use.php

fix: don't loose type of `useitem`

---

tests/new/__snapshots__/jsfmt.spec.js.snap
tests/new/new.php

tests: new `static`

---

src/printer.js
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php

fix: indent in `heredoc`

---

src/printer.js
tests/case/__snapshots__/jsfmt.spec.js.snap
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

fixes #171 
Some hack, if somebody have time to do PR in prettier - welcome! We need `invertLine`, logic as line, but versa vice, i.e. when group breaks we should insert `" "`, if does not break - insert `hardline`

feat: method declaration PSR compat

---

src/printer.js
src/util.js
tests/inline/__snapshots__/jsfmt.spec.js.snap
tests/inline/mixed.php

Part 2. look better and better :star:

feat: better support `inline` inside control structures

---

tests/shebang/__snapshots__/jsfmt.spec.js.snap
tests/shebang/jsfmt.spec.js
tests/shebang/shebang.php

tests: shebang

---

src/printer.js
src/util.js
tests/inline/__snapshots__/jsfmt.spec.js.snap
tests/inline/declare.php
tests/inline/mixed-3.php
tests/inline/mixed-4.php

fix: `declare` statement and `inline`

---

tests/clone/__snapshots__/jsfmt.spec.js.snap
tests/clone/clone.php

tests: clone

---

tests/errors/__snapshots__/jsfmt.spec.js.snap
tests/errors/errors.php

Just tests.
@czosel @mgrip Next PR's will be only in Monday, feel free to merge and rebase.

tests: throw

---

src/clean.js
src/printer.js
tests/echo/__snapshots__/jsfmt.spec.js.snap
tests/echo/echo.php
tests/echo/jsfmt.spec.js
tests/print/__snapshots__/jsfmt.spec.js.snap
tests/print/jsfmt.spec.js
tests/print/print.php
tests/sys/__snapshots__/jsfmt.spec.js.snap

Improve `echo` and `print` :star:

fix: echo indent

---

src/printer.js
tests/exit/__snapshots__/jsfmt.spec.js.snap
tests/exit/exit.php

feat: improve exit arguments output

---

src/printer.js
tests/switch/__snapshots__/jsfmt.spec.js.snap
tests/switch/empty_lines.php
tests/switch/empty_switch.php
tests/switch/switch.php

Based on https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L1631. Also all tests were adapted.
P.S. We don't break anything in switch statement :star:

feat: improve `switch` output

---

src/printer.js
tests/new/__snapshots__/jsfmt.spec.js.snap
tests/new/new.php

[WIP] feat: improve `new` output

---

src/clean.js
src/printer.js
tests/case/__snapshots__/jsfmt.spec.js.snap
tests/include/__snapshots__/jsfmt.spec.js.snap
tests/include/include.php
tests/include/single.php

feat: use `include` form without parenthesis

---

tests/staticlookup/__snapshots__/jsfmt.spec.js.snap
tests/staticlookup/jsfmt.spec.js
tests/staticlookup/staticlookup.php

tests: `staticlookup` node

---

src/clean.js
src/printer.js
tests/echo/__snapshots__/jsfmt.spec.js.snap
tests/echo/echo.php
tests/include/__snapshots__/jsfmt.spec.js.snap
tests/include/include.php
tests/print/__snapshots__/jsfmt.spec.js.snap
tests/print/print.php
tests/return/__snapshots__/jsfmt.spec.js.snap
tests/return/return.php

feat: better handle parens inside parens

---

tests/silent/__snapshots__/jsfmt.spec.js.snap
tests/silent/jsfmt.spec.js
tests/silent/silent.php

tests: `silent` node

---

src/printer.js

refactor: little fix

---

tests/list/__snapshots__/jsfmt.spec.js.snap
tests/list/jsfmt.spec.js
tests/list/list.php

Just tests, but found bug in parser (https://github.com/glayzzle/php-parser/issues/137). We can merge this now as is and when bug will be solve uncomment line and update snapshot

tests: `list` node

---

package.json
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/class.php
yarn.lock

Tests: class docblocks with use group, update php-parser

---

src/printer.js
tests/do/__snapshots__/jsfmt.spec.js.snap
tests/if/__snapshots__/jsfmt.spec.js.snap
tests/if/if.php
tests/list/__snapshots__/jsfmt.spec.js.snap
tests/switch/__snapshots__/jsfmt.spec.js.snap
tests/while/__snapshots__/jsfmt.spec.js.snap
tests/while/while.php

All refactor :+1: Right now we have one function for printing body of control structure

feat: improve output empty control structures

---

src/clean.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php
tests/comments/__snapshots__/jsfmt.spec.js.snap

* adding test for array desctructuring
* fixing bug in ast clean function

tests: adding tests for destructure

---

src/printer.js
src/util.js
tests/echo/__snapshots__/jsfmt.spec.js.snap
tests/list/__snapshots__/jsfmt.spec.js.snap
tests/print/__snapshots__/jsfmt.spec.js.snap

https://github.com/prettier/plugin-php/issues/256

fix: refactor newline logic to fix trailing comments

---

src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/comments.php

https://github.com/prettier/plugin-php/issues/252
Also fixing fwd slashes getting stripped out of comments

fix: several comment bugfixes

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/no_code.php

Handle files which contain nothing but comments

---

src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/array.php

https://github.com/prettier/plugin-php/issues/273
Also refactoring the getCommentChildNodes to make it more scalable

fix: nested array comments

---

tests/string/__snapshots__/jsfmt.spec.js.snap
tests/string/string.php

Looks like it's working already :smile: 
Fixes #267

Tests: Backslash escaping

---

src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/bin.php

fix: print comments inside `bin`

---

src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/functions.php
tests/comments/method.php

fixes #278
Some comment in incorrect places. Let's fix it in other PR :+1: 
Issue https://github.com/prettier/plugin-php/issues/286

fix: print comments in function and method arguments

---

src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/comments.php

Retif comments support

---

src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/comments.php

Too lazy to create an issue for this :sweat_smile:

Support comments in "new" node

---

src/util.js
tests/silent/__snapshots__/jsfmt.spec.js.snap
tests/silent/silent.php

Add semicolon after `silent` nodes

---

src/printer.js
tests/traits/__snapshots__/jsfmt.spec.js.snap
tests/traits/traits.php

Fix private traitalias

---

src/printer.js
tests/literals/__snapshots__/jsfmt.spec.js.snap
tests/literals/literals.php

Use node.raw in heredoc nodes

---

src/util.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/jsfmt.spec.js
tests/parens/new.php

fix: print semicolon fi statement inside `parens`

---

src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/echo.php

Related issue https://github.com/prettier/plugin-php/issues/231 and some comments look incorrectly place

fix: print comments inside `echo` node

---

src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/include.php

We have extra indent, let's fix in other PR

fix: print comments inside incide node

---

src/printer.js
tests/inline/__snapshots__/jsfmt.spec.js.snap

:star2: Now we don't lose `\n` and output mixed content as is

fix: use `raw` property for output `inline` node

---

src/printer.js
tests/literals/__snapshots__/jsfmt.spec.js.snap
tests/literals/literals.php

Fixes #294 
There are probably some more node types one could embed a heredoc/nowdoc inside of?

Add linebreak for heredoc/nowdoc inside call

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/comments.php

fix: adding dangling comments for parens

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

fix: extra space for `static` property

---

src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/throw.php

fixes #311
Issue around ugly https://github.com/prettier/plugin-php/issues/318

fix: print comments in `throw` node

---

src/printer.js
src/util.js
tests/call/__snapshots__/jsfmt.spec.js.snap
tests/call/call.php
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/array.php
tests/trailing_commas/__snapshots__/jsfmt.spec.js.snap
tests/trailing_commas/trailing_commas.php

fixes #313
Also add tests for comments and fix break array when array have leading comment.

fix: don't add extra newline and `,` in empty array

---

src/printer.js
src/util.js
tests/literals/__snapshots__/jsfmt.spec.js.snap
tests/literals/literals.php

Fix heredoc/nowdoc inside arrays

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

fix: extra space before static property

---

tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/comments.php

fixes #310
Looks like all already works, just add tests :+1:

tests: `//` inside comments

---

src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/empty.php
tests/comments/isset.php
tests/comments/list.php
tests/comments/unset.php

fix: output comments in `list`, `isset`, `unset`, and `empty` nodes

---

src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/print.php

Ugly, let's fix it in other PR

fix: output comments in `print` node

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/if/__snapshots__/jsfmt.spec.js.snap
tests/if/if.php
tests/retif/__snapshots__/jsfmt.spec.js.snap
tests/retif/jsfmt.spec.js
tests/retif/retif.php

fix: add newline in assign before `?:` operator

---

src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/class.php

https://github.com/prettier/plugin-php/issues/325

fix: interface comments

---

package.json
src/printer.js
tests/string/__snapshots__/jsfmt.spec.js.snap
tests/string/string.php
yarn.lock

Fix escaping in encapsed nodes

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/break.php
tests/comments/continue.php

fix: output comments in `break` and `continue` node

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/exit.php

Some comments are ugly, let's fix it in other PR

fix: output all comments in `exit` node

---

src/index.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/bin.php
tests/comments/call.php
tests/comments/class.php
tests/comments/do.php
tests/comments/echo.php
tests/comments/for.php
tests/comments/foreach.php
tests/comments/functions.php
tests/comments/heredoc.php
tests/comments/if.php
tests/comments/method.php
tests/comments/nowdoc.php
tests/comments/parameter.php
tests/comments/switch.php
tests/comments/usegroup.php
tests/comments/variadic.php
tests/comments/while.php

fixes #347 
Also:
1. Refactor some places.
2. Fix comments in `variadic` node
3. Fix comment in `use` node inside alias

test: more comments tests

---

tests/yield/__snapshots__/jsfmt.spec.js.snap
tests/yield/yield.php

Very ugly, any ideas how we can print this better?

tests: `yield` node

---

src/printer.js
src/util.js

refactor: one function for `semicolon`

---

package.json
yarn.lock

https://github.com/glayzzle/php-parser/releases/tag/3.0.0-alpha1

chore: updating parser to 3.0 pre-release

---

src/printer.js
tests/list/__snapshots__/jsfmt.spec.js.snap
tests/list/list.php

Related issue https://github.com/glayzzle/php-parser/issues/150

fix: print key/value `list` node

---

tests/declare/__snapshots__/jsfmt.spec.js.snap
tests/declare/declare.php

Tests: declare without curlies

---

src/printer.js
src/util.js
tests/call/__snapshots__/jsfmt.spec.js.snap
tests/call/call.php
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/comments.php
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/inline/__snapshots__/jsfmt.spec.js.snap
tests/member_chain/__snapshots__/jsfmt.spec.js.snap
tests/new/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/new.php
tests/retif/__snapshots__/jsfmt.spec.js.snap
tests/retif/retif.php

https://github.com/prettier/plugin-php/issues/390
pretty much copying logic from prettier - I checked all of the updated snapshots and they matched prettierjs output

fix: printArgumentsList

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/eval/__snapshots__/jsfmt.spec.js.snap
tests/exit/__snapshots__/jsfmt.spec.js.snap
tests/if/__snapshots__/jsfmt.spec.js.snap
tests/if/if.php
tests/new/__snapshots__/jsfmt.spec.js.snap
tests/operations/__snapshots__/jsfmt.spec.js.snap
tests/operations/operations.php
tests/retif/__snapshots__/jsfmt.spec.js.snap
tests/silent/__snapshots__/jsfmt.spec.js.snap
tests/switch/__snapshots__/jsfmt.spec.js.snap

fix: updating binary printing logic

---

src/clean.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
tests/if/__snapshots__/jsfmt.spec.js.snap
tests/if/if.php

Closes https://github.com/prettier/plugin-php/issues/242 https://github.com/prettier/plugin-php/issues/214 and https://github.com/prettier/plugin-php/issues/211

tests: add test for if and class

---

package.json
src/index.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/if.php
yarn.lock

fixes #283 fixes #318
updating to use new `isBlockComment` api from prettier https://github.com/prettier/prettier/pull/4347

fix: inline comments

---

src/comments.js
src/index.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/functions.php
tests/comments/method.php

fix: function argument comments

---

package.json
src/printer.js
tests/call/__snapshots__/jsfmt.spec.js.snap
tests/case/__snapshots__/jsfmt.spec.js.snap
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/declare/__snapshots__/jsfmt.spec.js.snap
tests/declare/declare.php
tests/list/__snapshots__/jsfmt.spec.js.snap
tests/new/__snapshots__/jsfmt.spec.js.snap
tests/return/__snapshots__/jsfmt.spec.js.snap
yarn.lock

fix: nested declare

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/if.php

Fix inline comments before else if

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/for.php

fix: shortform for loop breaking comment

---

src/util.js
tests/variable/__snapshots__/jsfmt.spec.js.snap
tests/variable/single.php

fix: add semicolon for single variable

---

tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/inline.php

tests: comment before inline

---

src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php
tests/comments/__snapshots__/jsfmt.spec.js.snap

fix: better print nested array

---

tests/staticlookup/__snapshots__/jsfmt.spec.js.snap
tests/staticlookup/staticlookup.php

tests: staticlookup

---

src/printer.js
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/nowdoc.php

fix: formatting heredoc/nowdoc inside arrays and function calls

---

src/printer.js
tests/member_chain/__snapshots__/jsfmt.spec.js.snap
tests/member_chain/member_chain.php
tests/member_chain/staticlookup.php

feat: better print `staticlookup` nodes

---

package.json
src/index.js
src/pragma.js
tests/insert-pragma/__snapshots__/jsfmt.spec.js.snap
tests/insert-pragma/jsfmt.spec.js
tests/insert-pragma/pragma-alreadyinserted.php
tests/insert-pragma/pragma-nodocblock.php
tests/insert-pragma/pragma-sparsedocblock.php
tests/insert-pragma/pragma-weirddocblock-alt.php
tests/insert-pragma/pragma-weirddocblock.php
tests/insert-pragma/pragma-withdocblock.php
tests/require-pragma/__snapshots__/jsfmt.spec.js.snap
tests/require-pragma/file-with-alt-pragma.php
tests/require-pragma/file-with-pragma.php
tests/require-pragma/file-without-pragma.php
tests/require-pragma/jsfmt.spec.js
yarn.lock

Closes https://github.com/prettier/plugin-php/issues/454.

implements --require-pragma and --insert-pragma

---

tests/string/__snapshots__/jsfmt.spec.js.snap
tests/string/multiline.php

Tests: Multiline strings

---

src/printer.js
tests/string/__snapshots__/jsfmt.spec.js.snap
tests/string/multiline.php
tests/string/string.php

fix: don't break assign with multiline

---

src/printer.js
tests/inline/__snapshots__/jsfmt.spec.js.snap
tests/inline/mixed-7.php

Respect short echo syntax

---

tests/foreach/__snapshots__/jsfmt.spec.js.snap
tests/foreach/foreach.php

tests: `destructuring` in foreach

---

src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php

fix: print empty lines inside arrays

---

tests/include/__snapshots__/jsfmt.spec.js.snap
tests/include/include.php

fixes #74
Based on https://github.com/prettier/plugin-php/issues/74#issuecomment-379488817

tests: ensure we don't break code

---

src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php
tests/call/__snapshots__/jsfmt.spec.js.snap

Based on https://github.com/prettier/plugin-php/issues/114#issuecomment-404909041

fix: better print `call` as value in array

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/call.php

Fix comments in call expression without arguments

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/anonymous.php
tests/comments/__snapshots__/jsfmt.spec.js.snap

Based on https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#8-anonymous-classes

feat: better print anonymous classes

---

src/printer.js
tests/string/__snapshots__/jsfmt.spec.js.snap
tests/string/string.php

Remove todo and uncomment tests, all tested

refactor: string

---

src/printer.js
tests/cast/__snapshots__/jsfmt.spec.js.snap
tests/cast/cast.php

Also find bug in parser, todo and link in source code
From http://php.net/manual/en/language.types.type-juggling.php#language.types.typecasting

fix: binary cast

---

src/printer.js
tests/retif/__snapshots__/jsfmt.spec.js.snap
tests/retif/retif.php

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAbgQwE4AIC8uAFKjABYCWAzgHQAmmMmARplXAAqNkA6UuAwQID8uAOTwqMMUlylKtVuy7lcNXABEAkgCUAogGEAKgHkdATQD6AZT0cAgjvumduANTiGTJXDEBKdz4hIRIAB25cUW19YzMrWwcnF3c5cNVZVDSyPwBuEAAaEAhQmApoKmRQHGwIAHcubAQKlEx0CAo6ApBmbEwwAGs4GGtwsAooAHNkGGwAVzhC8fZsGA5eiYBbTGQAM0wAG3ZCgCsqAA8AIV6BoetMDbgAGXG4XYOjkHDsZeQQHf26l1QthxjAAOodcjIAAcAAZCsCIOwwb1Qr9gXBluhXoVGgBHWYURprTCbbZIPaHBYgdgbCjTObUqjjCb7OAARVmEHgbyphW8ELoUKQACZ+b0KPsWQYIBstr8oNAcSBZuwjCxmpT2ABfbVAA

feat: better print `retif` node in parens

---

tests/block/__snapshots__/jsfmt.spec.js.snap
tests/block/block.php
tests/block/jsfmt.spec.js

test: multiple nested blocks

---

src/printer.js
tests/inline/__snapshots__/jsfmt.spec.js.snap
tests/inline/inline.php

fix: alignment statement in block node with inline node

---

CONTRIBUTING.md

I had some trouble getting started working on this. These changes to CONTRIBUTING.md might help a bit.

Improve developer onboarding

---

src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php
tests/member_chain/__snapshots__/jsfmt.spec.js.snap

Keep linebreaks in arrays

---

src/comments.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap

Preserve linebreaks in only-comment blocks

---

src/comments.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap

Fix comment-only blocks and one-line-expressions

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/return.php

fix: empty return with comments

---

src/printer.js
tests/foreach/__snapshots__/jsfmt.spec.js.snap
tests/foreach/foreach.php

fix: better print key/value in foreach

---

src/printer.js
tests/echo/__snapshots__/jsfmt.spec.js.snap
tests/echo/echo.php
tests/print/__snapshots__/jsfmt.spec.js.snap
tests/print/print.php

feat: better print `echo`

---

src/printer.js
tests/functions/__snapshots__/jsfmt.spec.js.snap
tests/functions/functions.php

Also refactor logic and remove hack.

fix: move bracket on newline in long function

---

src/printer.js
src/util.js
tests/assign/__snapshots__/jsfmt.spec.js.snap
tests/assign/assign.php
tests/assign/jsfmt.spec.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/member_chain/__snapshots__/jsfmt.spec.js.snap
tests/offsetlookup/__snapshots__/jsfmt.spec.js.snap

fixes #537
Also refactor `*lookup` nodes

fix: better print `assign` and `*loopup` nodes

---

src/util.js
tests/inline/__snapshots__/jsfmt.spec.js.snap
tests/inline/mixed-36.php
tests/inline/mixed-37.php

fix: alignment for inline nodes

---

src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php

feat: better print number in entry

---

src/printer.js
src/util.js
tests/bin/__snapshots__/jsfmt.spec.js.snap
tests/bin/bin.php
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/member_chain/__snapshots__/jsfmt.spec.js.snap
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/retif/__snapshots__/jsfmt.spec.js.snap

:star: :star: :star: 
All new examples will be tested on prettier playground and all output same as prettier

Fix better print binary

---

package.json
src/parser.js
src/util.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/cast/__snapshots__/jsfmt.spec.js.snap
tests/comments/__snapshots__/jsfmt.spec.js.snap
yarn.lock

fixes #541 Wait review to continue work on update `3.0.0-prerelease.1`

feat: update parser

---

src/printer.js
tests/closure/__snapshots__/jsfmt.spec.js.snap
tests/closure/closure.php

fix: closure by ref

---

tests/variable/__snapshots__/jsfmt.spec.js.snap
tests/variable/variable.php

test: deep $

---

tests/silent/__snapshots__/jsfmt.spec.js.snap
tests/silent/silent.php

test: space in silent node

---

tests/case/__snapshots__/jsfmt.spec.js.snap
tests/case/case.php

test: cast case

---

src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/foreach/__snapshots__/jsfmt.spec.js.snap
tests/list/__snapshots__/jsfmt.spec.js.snap
tests/retif/__snapshots__/jsfmt.spec.js.snap
tests/retif/retif.php

Logic from prettier https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L1270

feat: better print entry node

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/traits/__snapshots__/jsfmt.spec.js.snap
tests/traituse/__snapshots__/jsfmt.spec.js.snap
tests/traituse/jsfmt.spec.js
tests/traituse/traituse.php

feat: better print `traituse` node

---

src/printer.js
tests/offsetlookup/__snapshots__/jsfmt.spec.js.snap
tests/offsetlookup/offsetlookup.php
tests/propertylookup/__snapshots__/jsfmt.spec.js.snap
tests/propertylookup/propertylookup.php
tests/staticlookup/__snapshots__/jsfmt.spec.js.snap
tests/staticlookup/staticlookup.php

refactor: lookup nodes

---

src/printer.js
tests/property/__snapshots__/jsfmt.spec.js.snap
tests/property/jsfmt.spec.js
tests/property/property.php

feat: better print `property` node

---

src/printer.js

refactor: move space to keyword

---

src/comments.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/for.php
tests/comments/foreach.php

feat: better print for/foreach comments

---

src/needs-parens.js
tests/kitchen_sink/__snapshots__/jsfmt.spec.js.snap
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/control-structures.php

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACAzgdwJYzAC1QAoASedGASlWAB0pVGnGwBDdOYo08mVAXn6oAjJTFJ6zKUxLYBqAEwBuSdNRsOqMnAoChCiQzXNZ8gMwqj0gCZwAZqwCuAGxiHjJuUOGXmAXxAAGhAIAAcYbGh0ZFBWACc4iEwABXiEaJRWADcIbGsgkAAjONYwAGs4GABlUNLsKABzZBg4xzhg+o44mGSShoBbVmQHZw5ggCt0AA8AIRLyyqrWfrgAGXq4YdZR9pBauK7kItZCgE9naALQuPqYAHU8mHxkAA4ABmDriA47ktCj646OBxLKbYJxOAAR0c2AhvVYAyGSBGYxAHH62GarV26HqDWccAAio4IPAtjtgjATg9rE9kApKSVsM48QBhCD9QZHKDQMEgRwcAAqJwyKLgfj8QA

feat: feat avoid parens around control strcuture

---

tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/unnecessary.php

test: parens in default function argument

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/block.php

feat: avoid unnecessary parens in block node

---

tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/return.php

test: parens return

---

src/printer.js
src/util.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/parameter/__snapshots__/jsfmt.spec.js.snap
tests/parameter/jsfmt.spec.js
tests/parameter/parameter.php

feat: better print parameter node

---

src/needs-parens.js

fix: typo in condition for parens for control structure body

---

tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/break.php
tests/parens/continue.php

test: `continue` and `break` nodes

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/include.php

Also add tests for include and fix behavior for `bin` node, here issue about how better should looks `print` node https://github.com/prettier/plugin-php/issues/611

refactor: need parens code

---

src/needs-parens.js
src/util.js
tests/bin/__snapshots__/jsfmt.spec.js.snap
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/echo/__snapshots__/jsfmt.spec.js.snap
tests/if/__snapshots__/jsfmt.spec.js.snap
tests/include/__snapshots__/jsfmt.spec.js.snap
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/bin.php
tests/retif/__snapshots__/jsfmt.spec.js.snap
tests/return/__snapshots__/jsfmt.spec.js.snap
tests/silent/__snapshots__/jsfmt.spec.js.snap

I could have missed something because it's really hard, just create a new issue if you find that I made a mistake

feat: parens around bin node

---

src/needs-parens.js
tests/bin/__snapshots__/jsfmt.spec.js.snap
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/bin.php

fix: bin string concatenation

---

src/printer.js
src/util.js
tests/echo/__snapshots__/jsfmt.spec.js.snap
tests/echo/echo.php
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/nowdoc.php

fix: `nowdoc/heredoc` newline

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/array.php
tests/parens/cast.php

My bug, also refactor code and little fix for array

fix: broken cast in `retif` and `silence` node

---

src/clean.js
src/comments.js
src/printer.js
src/util.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/halt/__snapshots__/jsfmt.spec.js.snap
tests/halt/other-single.php
tests/halt/single.php
tests/string/__snapshots__/jsfmt.spec.js.snap
tests/string/string.php
tests/variable/__snapshots__/jsfmt.spec.js.snap
tests/variable/variable.php
tests_config/run_spec.js

[WIP] fix: ast compare

---

src/clean.js
src/printer.js
tests/identifier/__snapshots__/jsfmt.spec.js.snap
tests/identifier/identifier.php
tests/identifier/jsfmt.spec.js

rare use case, but we have bug with this

fix: identifier printing

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/pre-post.php
tests/parens/unary.php

feat: avoid unnecessary parens around pre and post nodes

---

src/needs-parens.js
src/printer.js
tests/static/__snapshots__/jsfmt.spec.js.snap
tests/static/static.php

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEASAhgGhwCMBuAHSnS2wDc4AnATwDUGW3WnP2uO+mAMtADmzXPQCWuIukK1+PRd2ULuQqKPFSZccpQw4wmALyYATHqqGTmAIz2Hjp85eu37j59eWD2eAGcYACU4XFRURhCwiPVhG1s5fwgAWzgAeRgACwYo8MjQvNixSWl0GzM5aDgAWQh6OFyYkWLtMtMAZh9qXBsAcjpeQaVVEaGVMYVYgGUYSQ1eruI+geGJtdWN8Y3p2Yl5-ApMI6XTftHN862ry7YdueEFiis8GwBtfrCAVzhewl6ILIMAC0NC+PwAuosXqZ3qDUN9fph-oD6CCwYjkdlUQCsUCccD8diUXjiYSSbi4QjIU9fD0YR94T8-mTKRC5EQ3gyEcziazetT9N1OXyeRT0aKCaSpbiybLpcC+eD2cLxUiWarMZKZfKidq9VqFeiBc86ZhgL0ANZwRi9JBIkVq4lWm12zWovkAXyhpuAh2Oluttvt4r9RzdQOdQfDfIoXppQtM5sjrod4eTjrFjN6HuViYDLuDWYlqPT0fRccFOB9oeOYdLIprtbTgdd6qzFDIMBzNewHMTjf99ZDUFrTbJpbbCJrFZNfUC916mAA1Ej53sHsvV7t5pvemudyu99uN4f9yetwvd2fHpW8LmL+vF6fj0+Hwe3+ej5fn9+P6+v4+JAgPgIAQAADjAEjQP4yCgOI9AQAA7gACuICAwSguA0BAEgACbASARD0LgYBWjAUxgSR67ILM3 …

feat: better print static

---

src/comments.js

As in prettier https://github.com/prettier/prettier/blob/master/src/language-js/comments.js
It looks like we are already close to a stable release, so my roadmap:
- Improve comments output on this week.
- Improve `inline` output on next week.
Also refactoring/fixes edge cases/maybe update parser to master
And we can do stable release

refactor: comments

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/variable.php

From here https://github.com/prettier/prettier/blob/master/src/language-js/comments.js#L690

feat: better print variable comments

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/array.php

From prettier, same logic for `{prop: value}` handlePropertyComments

feat: better handle entry comments

---

src/comments.js
src/index.js
src/printer.js

Logic from prettier, also support comments in `alternative`, move `isBlockComment` to `commnets`. In next PR i will improve comments output in `if`

Refactor if node

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/retif/__snapshots__/jsfmt.spec.js.snap
tests/return/__snapshots__/jsfmt.spec.js.snap
tests/return/return.php

feat: avoid parens in `return` node

---

package.json
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/lookups.php
tests/staticlookup/__snapshots__/jsfmt.spec.js.snap
tests/staticlookup/staticlookup.php
tests/variable/__snapshots__/jsfmt.spec.js.snap
tests/variable/variable.php
yarn.lock

fix: parens before staticlookup node

---

tests/new/__snapshots__/jsfmt.spec.js.snap
tests/new/new.php

test: heredoc and nowdoc in `new` node

---

src/printer.js
src/util.js
tests/new/__snapshots__/jsfmt.spec.js.snap
tests/new/new.php

Without global variable, because it can be dangerous

refactor: anonymous class

---

tests/bin/__snapshots__/jsfmt.spec.js.snap
tests/bin/bin.php

test: test bin null coalescing nodes

---

src/printer.js
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php

Fix offset type encapsed

---

src/printer.js

refactor: encapsed node

---

tests/new/__snapshots__/jsfmt.spec.js.snap
tests/new/new.php

test: new static

---

src/printer.js

refactor: print `function`, `closure` and `method` nodes

---

src/printer.js
tests/classconstant/__snapshots__/jsfmt.spec.js.snap
tests/classconstant/classconstant.php

feat: better print `classconstant` node

---

tests/foreach/__snapshots__/jsfmt.spec.js.snap
tests/foreach/foreach.php

Just test.
Compare https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/PrettyPrinter/Standard.php with our output (also create issue for new node/modify in our parser for better printing).

test: ref in `foreach` node

---

src/printer.js
tests/call/__snapshots__/jsfmt.spec.js.snap
tests/call/call.php

fixes #510
Port: https://github.com/prettier/prettier/pull/5151

fix: break args when second arg is a ternary

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php
tests/variable/__snapshots__/jsfmt.spec.js.snap

feat: better print long stuff in encapsed

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/clone.php
tests/parens/new.php

fix: parens around new and clone node with call node

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/interface.php
tests/comments/trait.php

Handle comments in `interface` and `trait`

feat: better print classlike node comments

---

src/printer.js
tests/bin/__snapshots__/jsfmt.spec.js.snap
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/retif/__snapshots__/jsfmt.spec.js.snap
tests/retif/retif.php

feat: better print `retif` without `true` expression

---

src/printer.js
tests/retif/__snapshots__/jsfmt.spec.js.snap
tests/retif/retif.php

fix: print retif without true expr

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/control-structures.php

fix: parens around assign in control structures

---

src/printer.js

Just refactor, for future `implements`

refactor: class part

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
tests/comments/__snapshots__/jsfmt.spec.js.snap

Partial fix https://github.com/prettier/plugin-php/issues/167. In some cases ugly, but we already have a lot of ugly examples, i will fix it in next PR, hard to fix all cases in one PR

feat: better print multiple implements

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

In some cases still ugly, will be fixed and refactored in next PRs.
Next:
- Better print extends and implements together
- Refactor
- More tests with comments

feat: better print extends for class

---

src/printer.js

For future union `extends` with one class and multiple

refactor: print class part

---

src/printer.js

refactor: print class

---

tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/anonymous.php

test: anonymous class

---

.gitattributes
src/printer.js
tests/newline/__snapshots__/jsfmt.spec.js.snap
tests/newline/html-CRLF.php
tests/newline/html-LF.php
tests/newline/jsfmt.spec.js
tests_config/run_spec.js

fix: extra line in plain html with CRLF

---

.gitattributes
src/parser.js
tests/newline/__snapshots__/jsfmt.spec.js.snap
tests/newline/mixed-CRLF.php
tests/newline/mixed-LF.php

I think we have more problem with this in some cases, WIP on this

fix: pseudo inline node with CRLF

---

.appveyor.yml
README.md
src/pragma.js

/cc @vjeux looks we don't have permissions to add project https://ci.appveyor.com/project/prettier/plugin-php

ci: appveyor

---

.codecov.yml
.travis.yml
README.md
jest.config.js
package.json
yarn.lock

chore: add codecov

---

src/pragma.js

No tests, because prettier for pragma in test change newline on OS based newline
Also refactor

fix: do not mix LF and CRLF

---

tests/preserve_line/__snapshots__/jsfmt.spec.js.snap
tests/preserve_line/argument-list.php
tests/preserve_line/comments.php
tests/preserve_line/jsfmt.spec.js
tests/preserve_line/member-chain.php

Port https://github.com/prettier/prettier/tree/master/tests/preserve_line
Some comments for lookup nodes have incorrect position - issue https://github.com/prettier/plugin-php/issues/701

test: preserve line

---

.gitattributes
tests/require-pragma/__snapshots__/jsfmt.spec.js.snap
tests/require-pragma/file-without-pragma-and-no-docblock-CRLF.php
tests/require-pragma/file-without-pragma-and-no-docblock-LF.php.php

Just test to increase coverage

test: pragma

---

.eslintrc.yml
jest.config.js
jest.eslint.config.js

fixes #724
Also prettify config

chore: fix linting

---

README.md

As you guys probably figured out by now I've been working on other things and don't have much time to devote to this anymore 😢 I left my job where I was actively using php (as far as I know they're still using this plugin though!)
I'm happy to answer questions and help out where I can but I just don't have a ton of time to devote to this, so thought I could remove myself from the list of active maintainers. I'm still super excited to see this get to a 1.0 and become the gold standard for php formatting! ⭐️ Keep up the great work @evilebottnawi and @czosel! I'll be watching from the sideline 😄

Remove mgrip from active maintainers

---

tests/bin/__snapshots__/jsfmt.spec.js.snap
tests/bin/bin.php

test: bin `instanceof`

---

src/needs-parens.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/cast.php

Really **BIG BUG** bug https://github.com/glayzzle/php-parser/issues/172. Need fix in parser. Let's output parens around `cast` as is to avoid break code.

fix: cast and bin parens

---

tests/member_chain/__snapshots__/jsfmt.spec.js.snap
tests/member_chain/member_chain.php

test: member-chain with static

---

src/printer.js
tests/retif/__snapshots__/jsfmt.spec.js.snap
tests/return/__snapshots__/jsfmt.spec.js.snap
tests/return/return.php

Try to prettify `laravel/framework` and found some bugs, let's fix it

fix: indent return

---

src/printer.js
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php

Big bug, found in laravel/framework

fix: broken offset propertylookup node

---

src/printer.js
tests/member_chain/__snapshots__/jsfmt.spec.js.snap
tests/member_chain/staticlookup.php

problem in parser, issue created, also add `TODO`

fix: consistent print static member chain

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/cast.php

fix: bug with cast and parens

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/silent.php
tests/silent/__snapshots__/jsfmt.spec.js.snap

fix: parens around silence operator

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/method.php

fix: comments in empty parens

---

tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/assign.php

Test comments in multiple assign

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/call.php
tests/comments/empty.php
tests/comments/eval.php
tests/comments/isset.php
tests/comments/unset.php

Before we get error about we don't print comment

fix: trailing comment in call

---

src/comments.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/halt-1.php

feat: better print halt comments

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/include.php

fix: indent for `include` node with end of line comment

---

tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/usegroup.php

test: `usegroup` node comment

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/yield.php

fix: indent for `yield` with end of line comment

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/echo.php

fix: indent for `echo` node with end of line comment

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/declare.php
tests/declare/__snapshots__/jsfmt.spec.js.snap

Include:
- no errors for comments inside declare
- fix `indent` for `short`
- refactor

fix: `declare` comments

---

src/comments.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/full.php
tests/comments/namespace-1.php
tests/comments/namespace-2.php

Before we got `Error` about what we don't print comments

fix: comments into `namespace`

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/inline8.php

fixes #509 
Some `inline` nodes doesn't look good, but not related to the PR, let's fix it in next PRs

fix: extra comment and overlaps for inline nodes

---

src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php
tests/bin/__snapshots__/jsfmt.spec.js.snap
tests/bin/bin.php
tests/call/__snapshots__/jsfmt.spec.js.snap
tests/call/call.php
tests/echo/__snapshots__/jsfmt.spec.js.snap
tests/echo/echo.php
tests/eval/__snapshots__/jsfmt.spec.js.snap
tests/eval/eval.php
tests/exit/__snapshots__/jsfmt.spec.js.snap
tests/exit/exit.php
tests/if/__snapshots__/jsfmt.spec.js.snap
tests/if/if.php
tests/parameter/__snapshots__/jsfmt.spec.js.snap
tests/parameter/parameter.php
tests/property/__snapshots__/jsfmt.spec.js.snap
tests/property/property.php
tests/retif/__snapshots__/jsfmt.spec.js.snap
tests/retif/retif.php
tests/static/__snapshots__/jsfmt.spec.js.snap
tests/static/static.php

Now multileline string looks everywhere very good. Need same for encapsulated, do this in next PR

fix: better print multiline `string`

---

src/printer.js
tests/new/__snapshots__/jsfmt.spec.js.snap
tests/new/new.php

As do prettier https://prettier.io/playground/#N4Igxg9gdgLgprEAuEU4HcAEAxCEAUABgDqxwDOMp8l1FMhAlCADQgQAOMAltOcqACGAJ2ER0ABREJ+KQQDcI3ACasQAI2GCwAazgwAyh23coAc2QxhAVzhtT5OMJgStZgLaDkAM0EAbRzYAK3IADwAhLV19A0F3OAAZUzgff0CQY2FHYWQNQXUATz9oNQ5hUxgAdRUYAAtkAA4ABjYyiEdKrQ5csooneRS2YTgAR2tuYddBDy8kXwC7EEd3bksbRfJTMz84AEVrCHhUhbYYfOrlOuQAJlOtbj8tgGEId09cqGhBkGtHABV8rJ5o4AL4goA

fix: multiline string in `new` node

---

tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/namespace-3.php

test: comments after namespace

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/namespace-4.php
tests/comments/namespace-5.php
tests/comments/namespace-6.php
tests/comments/namespace-7.php
tests/comments/namespace-8.php
tests/comments/namespace-9.php
tests/inline/__snapshots__/jsfmt.spec.js.snap
tests/namespace/__snapshots__/jsfmt.spec.js.snap
tests/namespace/namespace-newline-after.php
tests/namespace/namespace-newline-before.php
tests/namespace/namespace-next-call.php
tests/namespace/namespace-no-newline-after.php
tests/namespace/namespace-no-newline-before.php
tests/namespace/nested-1.php
tests/parens/__snapshots__/jsfmt.spec.js.snap

fix: respect user input after `namespace`

---

src/printer.js
src/util.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/namespace-10.php
tests/comments/namespace-11.php
tests/comments/namespace-12.php
tests/comments/namespace-13.php
tests/comments/namespace-14.php
tests/comments/namespace-15.php
tests/comments/namespace-16.php
tests/comments/namespace-17.php
tests/comments/namespace-18.php
tests/comments/namespace-19.php
tests/comments/namespace-20.php
tests/namespace/__snapshots__/jsfmt.spec.js.snap
tests/parens/__snapshots__/jsfmt.spec.js.snap

In some cases we lose newline after namespace, let's fix it.

fix: newline after namespace

---

tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/try.php

From https://github.com/prettier/prettier/pull/5252/files

test: try comments

---

tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/declare-1.php
tests/comments/declare-10.php
tests/comments/declare-2.php
tests/comments/declare-3.php
tests/comments/declare-4.php
tests/comments/declare-5.php
tests/comments/declare-6.php
tests/comments/declare-7.php
tests/comments/declare-8.php
tests/comments/declare-9.php
tests/declare/__snapshots__/jsfmt.spec.js.snap
tests/declare/declare-newline-after-and-before.php
tests/declare/declare-newline-after-with-namespace.php
tests/declare/declare-newline-after.php
tests/declare/declare-newline-before.php
tests/declare/declare-no-newline-after-with-namespace.php
tests/declare/declare-no-newline-before-and-after-with-namespace.php
tests/declare/declare-no-newlines.php
tests/declare/declare-on-next-line-after-open-php-tag.php
tests/declare/declare-on-same-line-with-open-php-tag-with-namespace.php
tests/declare/declare-on-same-line-with-open-php-tag.php
tests/declare/declare-with-multiple-space-1.php
tests/declare/declare-with-multiple-space-2.php
tests/declare/declare-with-multiple-space.php
tests/declare/multiple.php

test: declare

---

tests/variable/__snapshots__/jsfmt.spec.js.snap
tests/variable/variable.php

Just test. Looks we catch bug in parser

test: variable variables

---

src/needs-parens.js
src/printer.js
tests/call/__snapshots__/jsfmt.spec.js.snap
tests/call/call.php

fix: call with lookup node

---

src/printer.js
tests/staticlookup/__snapshots__/jsfmt.spec.js.snap
tests/staticlookup/staticlookup.php

Also fix bug due parser problem

fix: inline `staticlookup` node with `static` keyword

---

src/printer.js
src/util.js
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/nowdoc.php

big bug with `nowdoc` and `heredoc` inside `bin`

fix: bin with `nowdoc` or `heredoc`

---

src/printer.js
tests/call/__snapshots__/jsfmt.spec.js.snap
tests/call/call.php
tests/eval/__snapshots__/jsfmt.spec.js.snap
tests/eval/eval.php

fix: eval multiline argument output

---

src/printer.js
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/nowdoc.php

refactor: `nowdoc` and `heredoc` nodes

---

tests/print/__snapshots__/jsfmt.spec.js.snap
tests/print/print.php

test: print

---

package.json
src/comments.js
src/needs-parens.js
src/printer.js
src/util.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/call.php
yarn.lock

chore(deps): update

---

src/printer.js
tests/declare/__snapshots__/jsfmt.spec.js.snap
tests/declare/declare-invalid.php
tests/declare/declare-multiple-statements-2.php
tests/declare/declare-multiple-statements.php

fix: multiple statement in nested `declare` node

---

src/printer.js
src/util.js
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/nowdoc.php

fix: nowdoc and heredoc with static node

---

src/util.js
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/nowdoc.php

fix: nowdoc and heredoc output in `case` node

---

src/util.js
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/nowdoc.php

fix: nowdoc and heredoc in `for` node

---

src/printer.js
src/util.js
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/nowdoc.php

Fix a lot of bugs with `nowdoc` and `heredoc`

fix: nowdoc and heredoc binary newline

---

src/comments.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap

Fix: dangling namespace comments. Fixes #793

---

src/comments.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/functions.php
tests/comments/method.php

fix: unstable function comments

---

tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/eval.php
tests/comments/exit.php

test: comments

---

package.json
yarn.lock

Do you guys want me to install dependabot on this repo so they always going to be up to date?
Example: https://github.com/prettier/tslint-config-prettier/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+sort%3Aupdated-desc
Of course we can adjust it to do updates live, daily, or weekly.

feat: Upgrade dependencies

---

README.md

Document supported options

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/silent.php

fix: don't add extra parens for silent operator

---

src/clean.js

refactor: remove unnecessary code

---

tests/classconstant/__snapshots__/jsfmt.spec.js.snap
tests/classconstant/classconstant.php

test: multiple classconstant

---

tests/declare/__snapshots__/jsfmt.spec.js.snap
tests/declare/multiple-directives.php

test: multiple declare directives

---

tests/empty/__snapshots__/jsfmt.spec.js.snap
tests/empty/empty.php
tests/empty/jsfmt.spec.js

test: empty

---

tests/unset/__snapshots__/jsfmt.spec.js.snap
tests/unset/jsfmt.spec.js
tests/unset/unset.php

test: unset

---

tests/isset/__snapshots__/jsfmt.spec.js.snap
tests/isset/isset.php
tests/isset/jsfmt.spec.js

test: isset

---

src/printer.js
tests/staticlookup/__snapshots__/jsfmt.spec.js.snap
tests/staticlookup/staticlookup.php

fixes #605 
fix really big bug + refactor

fix: add curly braces when it is necessary for staticlookup

---

tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php

test: encapsed output

---

src/util.js
tests/inline/__snapshots__/jsfmt.spec.js.snap
tests/inline/semicolon.php

fix: avoid semicolon in short echo

---

tests/staticlookup/__snapshots__/jsfmt.spec.js.snap
tests/staticlookup/staticlookup.php

Just tests, it is safe to remove parens here

test: staticlookup

---

tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/chains.php

test: comment in propertylookup

---

tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php

test: no newlines in encapsed

---

tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/call.php
tests/parens/lookups.php
tests/string/__snapshots__/jsfmt.spec.js.snap
tests/string/string.php
tests/variable/__snapshots__/jsfmt.spec.js.snap
tests/variable/variable.php

Just remove todo, all works as expected.

Refactor remove todo from tests

---

src/comments.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/trait.php
tests/traituse/__snapshots__/jsfmt.spec.js.snap

Fix comments in empty traitUse

---

tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/cast.php

fixes #827, already fixed in parser

test: parens and cast

---

README.md
src/options.js
src/printer.js
tests/trailing_commas/__snapshots__/jsfmt.spec.js.snap
tests/trailing_commas/jsfmt.spec.js

feat: new option for trailing comma

---

src/printer.js
tests/cast/__snapshots__/jsfmt.spec.js.snap
tests/cast/cast.php

fixes #539
Maybe I missed something, let's solve other edge cases after feedback/issues

fix: better print `assign` and `cast`

---

tests/bin/__snapshots__/jsfmt.spec.js.snap
tests/bin/bin.php

test: new syntax for `instanceof`

---

.eslintrc.yml
src/clean.js
src/comments.js
src/printer.js

Avoid misleading around `==` and problem with upgrade in future

refactor: eqeqeq eslint rule

---

src/printer.js
src/util.js

refactor: remove unused code

---

package.json
src/printer.js
tests/member_chain/__snapshots__/jsfmt.spec.js.snap
tests/staticlookup/__snapshots__/jsfmt.spec.js.snap
tests/staticlookup/staticlookup.php
tests/variable/__snapshots__/jsfmt.spec.js.snap
yarn.lock

Second update parser
fixes #888

chore: deps update parser

---

src/printer.js
tests/member_chain/__snapshots__/jsfmt.spec.js.snap
tests/member_chain/offsetlookup.php
tests/propertylookup/__snapshots__/jsfmt.spec.js.snap
tests/propertylookup/offsets.php

Includes:
- More test
- Remove unused code
- Fix member chain for `encapsed` and `literal`

refactor: code

---

tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/static.php

fixes #711
Do as prettier https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAwhAtrhGAHSkigGdioMaN1s8DYTaMAxCCOzHfQl2vV5MqrALzcGfZtUE9G-WTQBMABmUBGANwgANCAgAHGAEto5ZKACGAJxsQA7gAVbCCyisA3CCYAmekAAjGyswAGs4GABlQ1CTKABzZBgbAFc4fQALGFwAGwB1TJN4cliwOCi3YpNPYoBPZHByC3148jgbGCcQhNwrZAAzK1z2-QArcgAPACEQ8MioqwIAGXi4QeHRkAnJqPiE3LgARVSIeA2RjJBYm3abRsCrQLrc6ADDG3iYfL8YTOQAByqfQfCDtfIhQyND5wO6edb6GxwACOqRMSO6Vl6-SQQ0u+nauBMyTSV3I+0OJzO61xmyuMCeP18f2Qyn0KSsJly+2EOJAUGgCJAqXaABUnu48e0AL7SoA

test: comments in static node

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap

Partial https://github.com/prettier/plugin-php/issues/844

fix: indent constructor in new with comment

---

src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php
tests/list/__snapshots__/jsfmt.spec.js.snap
tests/list/list.php
tests/parens/__snapshots__/jsfmt.spec.js.snap

Ref: https://github.com/prettier/plugin-php/pull/797

feat: improved array and list associative break heuristic

---

src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/arrays.php
tests/assign/__snapshots__/jsfmt.spec.js.snap
tests/assign/assign.php

Also more tests
As do prettier https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASA7gBwPoEMAmAtgJZTYBGuATgHQH7aEICuAFMADpQAE3A5MXx8k-JlGYBaGBADmMgDZw+AGi68+MYjEXC1vfXwA8AZ0y4eYebmPGAvBxC5yE4pCgOAfIYD0p8178LKxt7EGMwKjgECUiCOCopOAAPGE8+bgBqPX0c7mxsVj4AWRY+AEpM7Nz1H0CPFT0+AAtIgDNhfgBiPi4AXzKAbhBlEAhMTWhjZFBqKgh0AAVqBCmUXAA3CEFhkHIqXDAAazgYAGUzMFIZZBgqZjgRpphCeQB1Jq04PzA4U5WtYjrLQAT2Q4BsO1IxniMAW+xkhFwyFauHk0JGACtjEkAEL7I4nU64JgAGVIcGRqPRICxSVOV0UAEVmBB4JS0Q8QGYqNCqGDKORgfJoDtMFRSDBXoIYE1kAAOAAMIzFEGhr32mDBYq+8XWFJGkQAjsxiJE4bgEUikCiOSNoSQbndOcYGXBmayKdaqZyYE4pfgZcgAEwjW64YjyK4AYQghERYKg0H1IGY0IAKk5Vjbob1ekA

fix: better print bin

---

src/printer.js
tests/brace-style/__snapshots__/jsfmt.spec.js.snap
tests/brace-style/methods.php

refactor: print function

---

src/printer.js

Simplify. Prepare for https://github.com/prettier/plugin-php/issues/929

refactor: simplify print function without arguments

---

README.md

Sublime Text [now supports](https://github.com/jonlabelle/SublimeJsPrettier/commit/0e7fdb5d3ef4c60ddf14de27dfb6b4a6e721f56a) Prettier PHP.

Add Sublime Text Editor Integration Support

---

.github/ISSUE_TEMPLATE/formatting.md

It should make sense to have the current version as the default. :)

Update issue template to the latest plugin version

---

.github/ISSUE_TEMPLATE/formatting.md

Basically copied 1:1 from the [Prettier template](https://raw.githubusercontent.com/prettier/prettier/master/.github/ISSUE_TEMPLATE/formatting.md). 👍

Recommend playground in issue template

---

.travis.yml

Just test on node@12 instead 11

ci: use node@12

---

package.json
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/bin.php
tests/parens/silent.php
tests/silent/__snapshots__/jsfmt.spec.js.snap
yarn.lock

fix: update `php-parser`

---

package.json
src/comments.js
src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/parameter.php
yarn.lock

fix: update php parser

---

package.json
tests/use/__snapshots__/jsfmt.spec.js.snap
tests/use/use.php
yarn.lock

fix: update php-parser

---

package.json
yarn.lock

fix: update parser

---

tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/new.php

test: comments in `new`

---

tests/parameter/__snapshots__/jsfmt.spec.js.snap
tests/parameter/spec.php

Just test spec on parameter (https://github.com/php/php-src/blob/master/Zend/zend_language_parser.y#L634)

test: spec parameter node

---

tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/bin.php

test: null coalescing

---

tests/assignref/__snapshots__/jsfmt.spec.js.snap
tests/assignref/assignref.php
tests/assignref/jsfmt.spec.js

fix: issue-806

---

tests/trailing_commas/__snapshots__/jsfmt.spec.js.snap
tests/trailing_commas/call.php
tests/trailing_commas/isset.php
tests/trailing_commas/unset.php

/cc @czosel 
It is just tests, feature will be in other PR

test: trailing comma function calls

---

README.md
src/options.js
src/printer.js
tests/trailing_commas/__snapshots__/jsfmt.spec.js.snap
tests/trailing_commas/call.php
tests/trailing_commas/isset.php
tests/trailing_commas/jsfmt.spec.js
tests/trailing_commas/unset.php

/cc @czosel 
+ some refactor, we need cover this cases, let's do it in other PRs

feat: trailing comma in function calls

---

src/util.js

refactor: utils

---

src/printer.js
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/comments/bin.php

fix: printing comments in bin

---

tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php

test: heredoc and nowdoc

---

tests/assignref/__snapshots__/jsfmt.spec.js.snap
tests/assignref/assignref.php

test: assignref with call

---

src/printer.js
tests/switch/__snapshots__/jsfmt.spec.js.snap

fix(switch): inconsistent line spreading

---

CONTRIBUTING.md

feat(docs): add hints on debugging and running tests

---

src/clean.js
src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/array/jsfmt.spec.js
tests/call/__snapshots__/jsfmt.spec.js.snap
tests/case/__snapshots__/jsfmt.spec.js.snap
tests/closure/__snapshots__/jsfmt.spec.js.snap
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/list/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/parameter/__snapshots__/jsfmt.spec.js.snap
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/preserve_line/__snapshots__/jsfmt.spec.js.snap
tests/property/__snapshots__/jsfmt.spec.js.snap
tests/staticlookup/__snapshots__/jsfmt.spec.js.snap
tests/sys/__snapshots__/jsfmt.spec.js.snap
tests/trailing_commas/__snapshots__/jsfmt.spec.js.snap

feat: deterministic printing of array shortform

---

src/printer.js
tests/assignref/__snapshots__/jsfmt.spec.js.snap
tests/assignref/assignref.php

fix(entry): fix array entry byref printing

---

src/pragma.js
tests/insert-pragma/__snapshots__/jsfmt.spec.js.snap
tests/insert-pragma/pragma-firstdocblockmidfile.php

Thought I'd give it a try. No idea if this is sane.

fix: insert pragma when first docblock mid-file (#1310)

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

Fixes #1336
Together with the other open PRs, this completes #854 :tada:

feat: add support for typed properties (PHP7.4)

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php

fix: nullable property types

---

src/util.js
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/nowdoc.php

fix: heredoc/nowdoc trailing newlines

---

tests/nowdoc/__snapshots__/jsfmt.spec.js.snap

Builds were [failing on master](https://github.com/prettier/plugin-php/runs/549446230) - not exactly sure why we didn't see this on the PR itself. Either way, this should fix the build :upside_down_face:

fix: update snapshots

---

README.md

fix(README): remove "work in progress" sign

---

package.json

fix: update prettier peer dependency

---

package.json
tests/yield/__snapshots__/jsfmt.spec.js.snap
tests/yield/yield.php
yarn.lock

fix(deps): update parser

---

package.json
src/clean.js
src/options.js
src/printer.js
tests/array/__snapshots__/jsfmt.spec.js.snap
tests/list/__snapshots__/jsfmt.spec.js.snap
tests/list/jsfmt.spec.js
tests/trailing_commas/__snapshots__/jsfmt.spec.js.snap
yarn.lock

feat: convert list to short syntax automatically

---

package.json
src/printer.js
tests/encapsed/__snapshots__/jsfmt.spec.js.snap
tests/encapsed/encapsed.php
tests/encapsed/jsfmt.spec.js

fix: stop swallowing characters in indented heredoc

---

src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/comments/__snapshots__/jsfmt.spec.js.snap
tests/new/__snapshots__/jsfmt.spec.js.snap
tests/nowdoc/__snapshots__/jsfmt.spec.js.snap
tests/trailing_commas/__snapshots__/jsfmt.spec.js.snap

fix: space after anonymous class keyword

---

src/needs-parens.js
tests/parens/__snapshots__/jsfmt.spec.js.snap
tests/parens/lookups.php

Fix: broken method lookup on closure

---

package.json
src/printer.js
tests/errors/__snapshots__/jsfmt.spec.js.snap
tests/errors/errors.php
yarn.lock

fix(php8): non-capturing exception catches

---

README.md

Added PhpStorm/Jetbrains config guide

---

package.json
tests/trailing_comma_func/__snapshots__/jsfmt.spec.js.snap
tests/trailing_comma_func/function.php
yarn.lock

This was fixed in https://github.com/glayzzle/php-parser/pull/776
Fixes #1795

Update PHP parser to allow for dangling comma in use block

---

src/index.js
tests/ignore/__snapshots__/jsfmt.spec.js.snap
tests/ignore/ignore.php

Fix class const ignore formatting bug

---

package.json
tests/attributes/__snapshots__/jsfmt.spec.js.snap
tests/attributes/attributes.php
yarn.lock

fix: don't duplicate php8 attributes

---

src/printer.js
tests/attributes-trail-comma/__snapshots__/jsfmt.spec.js.snap
tests/attributes-trail-comma/attributes-trail-comma.php
tests/attributes-trail-comma/jsfmt.spec.js

Fix dangling commas on multiline attributes

---

src/printer.js
tests/attributes-trail-comma/__snapshots__/jsfmt.spec.js.snap
tests/attributes/__snapshots__/jsfmt.spec.js.snap

fix(attributes): remove extra line break

---

package.json
src/printer.js
src/util.js
tests/enum/__snapshots__/jsfmt.spec.js.snap
tests/enum/enum.php
tests/enum/jsfmt.spec.js
yarn.lock

Enum were added in PHP 8.1
https://www.php.net/manual/en/language.enumerations.php
I used the different example in the PHP doc to build the test case. If something is missing, I am happy to do a follow-up.

Enum support

---

package.json
src/options.js
src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
yarn.lock

Depends on 
Add support to readonly properties https://www.php.net/manual/en/language.oop5.properties.php#language.oop5.properties.readonly-properties

[8.1] - Add support of readonly properties

---

package.json
src/printer.js
tests/intersection-types/__snapshots__/jsfmt.spec.js.snap
tests/intersection-types/intersection.php
tests/intersection-types/jsfmt.spec.js
yarn.lock

Depends on https://github.com/glayzzle/php-parser/pull/883 
Union type and intersection type are basically the same thing.

[8.1] Add support for Intersection type

---

src/printer.js
tests/enum/__snapshots__/jsfmt.spec.js.snap
tests/match/__snapshots__/jsfmt.spec.js.snap
tests/match/jsfmt.spec.js

Fix trailing comma on match body

---

package.json
tests/attributes/__snapshots__/jsfmt.spec.js.snap
tests/attributes/attributes.php
tests/intersection-types/__snapshots__/jsfmt.spec.js.snap
tests/intersection-types/intersection.php
tests/namespace/__snapshots__/jsfmt.spec.js.snap
tests/namespace/keywords.php
yarn.lock

Fixes #1974, #1970, #1955, #1942, #1943, #1930

fix: bump parser

---

package.json
src/printer.js
tests/call/__snapshots__/jsfmt.spec.js.snap
tests/call/call.php
yarn.lock

feat: add PHP 8.1 first class callable support

---

src/printer.js
tests/match/__snapshots__/jsfmt.spec.js.snap

Format cases of match into separate lines.

---

package.json
tests/enum/__snapshots__/jsfmt.spec.js.snap
tests/enum/enum.php
yarn.lock

fix: enum as identifier

---

.github/workflows/nodejs.yml
package.json
tests/syntax-error/__snapshots__/jsfmt.spec.js.snap
yarn.lock

BREAKING CHANGE: This drops support for node v12.

chore!: upgrade dependencies

---

package.json
src/printer.js
tests/new/__snapshots__/jsfmt.spec.js.snap
tests/new/new.php
yarn.lock

Requires upstream fix in PHP-Parser
https://github.com/glayzzle/php-parser/pull/1020
closes #2082

Support expressions in new statement

---

package.json
src/printer.js
tests/class/__snapshots__/jsfmt.spec.js.snap
tests/class/class.php
yarn.lock

- Update php parser
- Add support for readonly class
Part of https://github.com/prettier/plugin-php/issues/2130

[8.2] readonly class

---

src/clean.js

It's supported since v2(not sure exact version, but not important since it's a debug feature).

Use `clean.ignoredProperties`

---

src/printer.js

Since we are going to drop support for Prettier<3, we can use [simplified `print()` introduced in Prettier v2.3.0](https://prettier.io/blog/2021/05/09/2.3.0#simplified-print-callback-10557httpsgithubcomprettierprettierpull10557-by-fiskerhttpsgithubcomfisker).

Simplify `print()`

---

src/comments.js
src/index.js
src/loc.js
src/printer.js
src/util.js

No need to use them from `options`.

Use `loc{Start,End}` directly

---

src/util.js

Use same pattern as Prettier core.
https://github.com/prettier/prettier/blob/7d56bc8752ccdb97dbbd7df66e3d5dbbac2b35b8/src/language-js/utils/index.js#L863-L884

Minor refactor to `getPrecedence`

---

README.md

See https://github.com/prettier/plugin-php/issues/2215#issuecomment-1684376930, the plugin now needs to be explicitly enabled

Document the fact that the plugin must be activated

---

package.json

Fix the `exports` field
